In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

folder_path = "/content/drive/MyDrive/Stock_Recommendation_Project/Data"

files = [f for f in os.listdir(folder_path) if f.endswith(".csv")]

print("Total CSV files:", len(files))
print("\nFirst 5 files:")
print(files[:5])

Total CSV files: 50

First 5 files:
['KOTAKBANK.csv', 'SHREECEM.csv', 'INFRATEL.csv', 'HDFC.csv', 'MM.csv']

In [ ]:
import pandas as pd
import os

sample_file = files[0]

df = pd.read_csv(os.path.join(folder_path, sample_file))

print("Sample File:", sample_file)

print("\nColumns:")
print(df.columns.tolist())

print("\nShape:")
print(df.shape)

print("\nFirst 5 Rows:")
print(df.head())

Sample File: KOTAKBANK.csv

Columns:
['Date', 'Symbol', 'Series', 'Prev Close', 'Open', 'High', 'Low', 'Last', 'Close', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume', '%Deliverble']

Shape:
(4985, 15)

First 5 Rows:
         Date    Symbol Series  Prev Close   Open    High     Low    Last  \
0  2000-01-03  KOTAKMAH     EQ      212.35  220.0  229.35  220.00  229.35
1  2000-01-04  KOTAKMAH     EQ      229.35  247.7  247.70  225.25  247.70
2  2000-01-05  KOTAKMAH     EQ      246.95  229.0  240.00  227.20  228.00
3  2000-01-06  KOTAKMAH     EQ      228.40  235.1  239.00  217.00  224.95
4  2000-01-07  KOTAKMAH     EQ      225.90  213.0  219.00  207.85  207.85

    Close    VWAP  Volume      Turnover  Trades  Deliverable Volume  \
0  229.35  229.13    7086  1.623640e+11     NaN                 NaN
1  246.95  244.12   73681  1.798729e+12     NaN                 NaN
2  228.40  233.75  105799  2.473093e+12     NaN                 NaN
3  225.90  226.84   40202  9.119546e+11     NaN                 NaN
4  208.85  209.94   24463  5.135747e+11     NaN                 NaN

   %Deliverble
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN

In [ ]:
print(df.isnull().sum())

Date                     0
Symbol                   0
Series                   0
Prev Close               0
Open                     0
High                     0
Low                      0
Last                     0
Close                    0
VWAP                     0
Volume                   0
Turnover                 0
Trades                2529
Deliverable Volume     196
%Deliverble            196
dtype: int64

In [ ]:
import pandas as pd
import os

all_data = []

for file in files:

    df = pd.read_csv(
        os.path.join(folder_path, file)
    )

    company = file.replace(".csv", "")

    df["Company"] = company

    all_data.append(df)

master_df = pd.concat(
    all_data,
    ignore_index=True
)

print("Shape:", master_df.shape)

master_df.head()

Shape: (235192, 16)

/tmp/ipykernel_416/1917293782.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  master_df = pd.concat(

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Company
0,2000-01-03,KOTAKMAH,EQ,212.35,220.0,229.35,220.00,229.35,229.35,229.13,7086,1.623640e+11,NaN,NaN,NaN,KOTAKBANK
1,2000-01-04,KOTAKMAH,EQ,229.35,247.7,247.70,225.25,247.70,246.95,244.12,73681,1.798729e+12,NaN,NaN,NaN,KOTAKBANK
2,2000-01-05,KOTAKMAH,EQ,246.95,229.0,240.00,227.20,228.00,228.40,233.75,105799,2.473093e+12,NaN,NaN,NaN,KOTAKBANK
3,2000-01-06,KOTAKMAH,EQ,228.40,235.1,239.00,217.00,224.95,225.90,226.84,40202,9.119546e+11,NaN,NaN,NaN,KOTAKBANK
4,2000-01-07,KOTAKMAH,EQ,225.90,213.0,219.00,207.85,207.85,208.85,209.94,24463,5.135747e+11,NaN,NaN,NaN,KOTAKBANK

In [ ]:
master_df.drop(
    columns=[
        "Series",
        "Last",
        "Trades",
        "Deliverable Volume",
        "%Deliverble"
    ],
    inplace=True
)

print(master_df.columns)

Index(['Date', 'Symbol', 'Prev Close', 'Open', 'High', 'Low', 'Close', 'VWAP',
       'Volume', 'Turnover', 'Company'],
      dtype='object')

In [ ]:
print(master_df.dtypes)

Date           object
Symbol         object
Prev Close    float64
Open          float64
High          float64
Low           float64
Close         float64
VWAP          float64
Volume         object
Turnover      float64
Company        object
dtype: object

In [ ]:
master_df["Date"] = pd.to_datetime(master_df["Date"])

In [ ]:
print(master_df.dtypes)

Date          datetime64[ns]
Symbol                object
Prev Close           float64
Open                 float64
High                 float64
Low                  float64
Close                float64
VWAP                 float64
Volume                object
Turnover             float64
Company               object
dtype: object

In [ ]:
print(master_df.isnull().sum())

Date          0
Symbol        0
Prev Close    0
Open          0
High          0
Low           0
Close         0
VWAP          0
Volume        0
Turnover      0
Company       0
dtype: int64

In [ ]:
master_df = master_df.sort_values(
    by=["Company", "Date"]
)

master_df = master_df.reset_index(drop=True)

In [ ]:
master_df.head()

,Date,Symbol,Prev Close,Open,High,Low,Close,VWAP,Volume,Turnover,Company
0,2007-11-27,MUNDRAPORT,440.00,770.00,1050.00,770.0,962.90,984.72,27294366,2.687719e+15,ADANIPORTS
1,2007-11-28,MUNDRAPORT,962.90,984.00,990.00,874.0,893.90,941.38,4581338,4.312765e+14,ADANIPORTS
2,2007-11-29,MUNDRAPORT,893.90,909.00,914.75,841.0,884.20,888.09,5124121,4.550658e+14,ADANIPORTS
3,2007-11-30,MUNDRAPORT,884.20,890.00,958.00,890.0,921.55,929.17,4609762,4.283257e+14,ADANIPORTS
4,2007-12-03,MUNDRAPORT,921.55,939.75,995.00,922.0,969.30,965.65,2977470,2.875200e+14,ADANIPORTS

In [ ]:
master_df.tail()

,Date,Symbol,Prev Close,Open,High,Low,Close,VWAP,Volume,Turnover,Company
235187,2021-04-26,ZEEL,188.00,190.6,191.10,185.10,186.40,187.35,8542755,1.600451e+14,ZEEL
235188,2021-04-27,ZEEL,186.40,188.0,192.95,186.80,188.15,189.41,14247767,2.698636e+14,ZEEL
235189,2021-04-28,ZEEL,188.15,188.8,190.60,187.10,189.10,188.85,8429439,1.591917e+14,ZEEL
235190,2021-04-29,ZEEL,189.10,190.8,191.65,186.00,186.55,187.44,9483009,1.777471e+14,ZEEL
235191,2021-04-30,ZEEL,186.55,185.3,190.95,183.65,185.60,187.53,11435285,2.144440e+14,ZEEL

In [ ]:
master_df["Daily_Return"] = (
    (master_df["Close"] - master_df["Open"])
    / master_df["Open"]
) * 100

In [ ]:
master_df["Volatility"] = (
    (master_df["High"] - master_df["Low"])
    / master_df["Close"]
) * 100

In [ ]:
master_df[[
    "Company",
    "Date",
    "High",
    "Low",
    "Close",
    "Volatility",
    "Daily_Return"
]].head()

      Company       Date     High    Low   Close  Volatility  Daily_Return
0  ADANIPORTS 2007-11-27  1050.00  770.0  962.90   29.078824     25.051948
1  ADANIPORTS 2007-11-28   990.00  874.0  893.90   12.976843     -9.156504
2  ADANIPORTS 2007-11-29   914.75  841.0  884.20    8.340873     -2.728273
3  ADANIPORTS 2007-11-30   958.00  890.0  921.55    7.378873      3.544944
4  ADANIPORTS 2007-12-03   995.00  922.0  969.30    7.531208      3.144453

In [ ]:
master_df["Momentum_5"] = (
    master_df.groupby("Company")["Close"]
    .pct_change(periods=5)
) * 100

In [ ]:
master_df[[
    "Company",
    "Date",
    "Close",
    "Momentum_5"
]].head(15)

       Company       Date    Close  Momentum_5
0   ADANIPORTS 2007-11-27   962.90         NaN
1   ADANIPORTS 2007-11-28   893.90         NaN
2   ADANIPORTS 2007-11-29   884.20         NaN
3   ADANIPORTS 2007-11-30   921.55         NaN
4   ADANIPORTS 2007-12-03   969.30         NaN
5   ADANIPORTS 2007-12-04  1041.45    8.157649
6   ADANIPORTS 2007-12-05  1082.45   21.092963
7   ADANIPORTS 2007-12-06  1081.30   22.291337
8   ADANIPORTS 2007-12-07  1102.40   19.624546
9   ADANIPORTS 2007-12-10  1075.40   10.946044
10  ADANIPORTS 2007-12-11  1047.65    0.595324
11  ADANIPORTS 2007-12-12  1036.80   -4.217285
12  ADANIPORTS 2007-12-13  1129.95    4.499214
13  ADANIPORTS 2007-12-14  1110.50    0.734761
14  ADANIPORTS 2007-12-17  1044.25   -2.896597

In [ ]:
master_df["Momentum_5"].describe()

count    234947.000000
mean          0.348672
std           6.176958
min         -95.412497
25%          -2.409051
50%           0.276571
75%           3.158123
max          68.464329
Name: Momentum_5, dtype: float64

In [ ]:
master_df["MA20"] = (
    master_df.groupby("Company")["Close"]
    .transform(lambda x: x.rolling(window=20).mean())
)

In [ ]:
master_df[[
    "Company",
    "Date",
    "Close",
    "MA20"
]].head(25)

       Company       Date    Close       MA20
0   ADANIPORTS 2007-11-27   962.90        NaN
1   ADANIPORTS 2007-11-28   893.90        NaN
2   ADANIPORTS 2007-11-29   884.20        NaN
3   ADANIPORTS 2007-11-30   921.55        NaN
4   ADANIPORTS 2007-12-03   969.30        NaN
5   ADANIPORTS 2007-12-04  1041.45        NaN
6   ADANIPORTS 2007-12-05  1082.45        NaN
7   ADANIPORTS 2007-12-06  1081.30        NaN
8   ADANIPORTS 2007-12-07  1102.40        NaN
9   ADANIPORTS 2007-12-10  1075.40        NaN
10  ADANIPORTS 2007-12-11  1047.65        NaN
11  ADANIPORTS 2007-12-12  1036.80        NaN
12  ADANIPORTS 2007-12-13  1129.95        NaN
13  ADANIPORTS 2007-12-14  1110.50        NaN
14  ADANIPORTS 2007-12-17  1044.25        NaN
15  ADANIPORTS 2007-12-18  1074.95        NaN
16  ADANIPORTS 2007-12-19  1066.90        NaN
17  ADANIPORTS 2007-12-20  1060.20        NaN
18  ADANIPORTS 2007-12-24  1156.80        NaN
19  ADANIPORTS 2007-12-26  1199.90  1047.1375
20  ADANIPORTS 2007-12-27  1211.65  1059.5750
21  ADANIPORTS 2007-12-28  1249.10  1077.3350
22  ADANIPORTS 2007-12-31  1268.80  1096.5650
23  ADANIPORTS 2008-01-01  1296.85  1115.3300
24  ADANIPORTS 2008-01-02  1307.45  1132.2375

In [ ]:
master_df["MA50"] = (
    master_df.groupby("Company")["Close"]
    .transform(lambda x: x.rolling(window=50).mean())
)

In [ ]:
master_df[[
    "Company",
    "Date",
    "Close",
    "MA20",
    "MA50"
]].head(60)

       Company       Date    Close       MA20      MA50
0   ADANIPORTS 2007-11-27   962.90        NaN       NaN
1   ADANIPORTS 2007-11-28   893.90        NaN       NaN
2   ADANIPORTS 2007-11-29   884.20        NaN       NaN
3   ADANIPORTS 2007-11-30   921.55        NaN       NaN
4   ADANIPORTS 2007-12-03   969.30        NaN       NaN
5   ADANIPORTS 2007-12-04  1041.45        NaN       NaN
6   ADANIPORTS 2007-12-05  1082.45        NaN       NaN
7   ADANIPORTS 2007-12-06  1081.30        NaN       NaN
8   ADANIPORTS 2007-12-07  1102.40        NaN       NaN
9   ADANIPORTS 2007-12-10  1075.40        NaN       NaN
10  ADANIPORTS 2007-12-11  1047.65        NaN       NaN
11  ADANIPORTS 2007-12-12  1036.80        NaN       NaN
12  ADANIPORTS 2007-12-13  1129.95        NaN       NaN
13  ADANIPORTS 2007-12-14  1110.50        NaN       NaN
14  ADANIPORTS 2007-12-17  1044.25        NaN       NaN
15  ADANIPORTS 2007-12-18  1074.95        NaN       NaN
16  ADANIPORTS 2007-12-19  1066.90        NaN       NaN
17  ADANIPORTS 2007-12-20  1060.20        NaN       NaN
18  ADANIPORTS 2007-12-24  1156.80        NaN       NaN
19  ADANIPORTS 2007-12-26  1199.90  1047.1375       NaN
20  ADANIPORTS 2007-12-27  1211.65  1059.5750       NaN
21  ADANIPORTS 2007-12-28  1249.10  1077.3350       NaN
22  ADANIPORTS 2007-12-31  1268.80  1096.5650       NaN
23  ADANIPORTS 2008-01-01  1296.85  1115.3300       NaN
24  ADANIPORTS 2008-01-02  1307.45  1132.2375       NaN
25  ADANIPORTS 2008-01-03  1275.80  1143.9550       NaN
26  ADANIPORTS 2008-01-04  1240.35  1151.8500       NaN
27  ADANIPORTS 2008-01-07  1227.25  1159.1475       NaN
28  ADANIPORTS 2008-01-08  1204.80  1164.2675       NaN
29  ADANIPORTS 2008-01-09  1180.25  1169.5100       NaN
30  ADANIPORTS 2008-01-10  1121.55  1173.2050       NaN
31  ADANIPORTS 2008-01-11  1085.85  1175.6575       NaN
32  ADANIPORTS 2008-01-14  1035.15  1170.9175       NaN
33  ADANIPORTS 2008-01-15  1049.55  1167.8700       NaN
34  ADANIPORTS 2008-01-16  1030.40  1167.1775       NaN
35  ADANIPORTS 2008-01-17  1020.90  1164.4750       NaN
36  ADANIPORTS 2008-01-18   994.60  1160.8600       NaN
37  ADANIPORTS 2008-01-21   825.05  1149.1025       NaN
38  ADANIPORTS 2008-01-22   735.55  1128.0400       NaN
39  ADANIPORTS 2008-01-23   857.00  1110.8950       NaN
40  ADANIPORTS 2008-01-24   814.15  1091.0200       NaN
41  ADANIPORTS 2008-01-25   865.70  1071.8500       NaN
42  ADANIPORTS 2008-01-28   820.80  1049.4500       NaN
43  ADANIPORTS 2008-01-29   840.75  1026.6450       NaN
44  ADANIPORTS 2008-01-30   830.45  1002.7950       NaN
45  ADANIPORTS 2008-01-31   837.65   980.8875       NaN
46  ADANIPORTS 2008-02-01   825.35   960.1375       NaN
47  ADANIPORTS 2008-02-04   856.10   941.5800       NaN
48  ADANIPORTS 2008-02-05   834.30   923.0550       NaN
49  ADANIPORTS 2008-02-06   807.50   904.4175  1029.868
50  ADANIPORTS 2008-02-07   796.25   888.1525  1026.535
51  ADANIPORTS 2008-02-08   784.05   873.0625  1024.338
52  ADANIPORTS 2008-02-11   711.20   856.8650  1020.878
53  ADANIPORTS 2008-02-12   681.30   838.4525  1016.073
54  ADANIPORTS 2008-02-13   670.95   820.4800  1010.106
55  ADANIPORTS 2008-02-14   709.80   804.9250  1003.473
56  ADANIPORTS 2008-02-15   728.75   791.6325   996.399
57  ADANIPORTS 2008-02-18   771.60   788.9600   990.205
58  ADANIPORTS 2008-02-19   763.90   790.3775   983.435
59  ADANIPORTS 2008-02-20   732.10   784.1325   976.569

In [ ]:
master_df["MA252"] = (
    master_df.groupby("Company")["Close"]
    .transform(lambda x: x.rolling(window=252).mean())
)

In [ ]:
master_df[[
    "Company",
    "Date",
    "Close",
    "MA20",
    "MA50",
    "MA252"
]].tail()

       Company       Date   Close      MA20     MA50       MA252
235187    ZEEL 2021-04-26  186.40  196.5925  206.604  193.260516
235188    ZEEL 2021-04-27  188.15  195.7400  206.052  193.381944
235189    ZEEL 2021-04-28  189.10  195.3900  205.489  193.556349
235190    ZEEL 2021-04-29  186.55  194.7200  204.918  193.702381
235191    ZEEL 2021-04-30  185.60  193.9525  204.380  193.833929

In [ ]:
master_df["MA20_Ratio"] = (
    master_df["Close"] / master_df["MA20"]
)

master_df["MA50_Ratio"] = (
    master_df["Close"] / master_df["MA50"]
)

master_df["MA252_Ratio"] = (
    master_df["Close"] / master_df["MA252"]
)

In [ ]:
master_df[[
    "Close",
    "MA20",
    "MA20_Ratio",
    "MA50",
    "MA50_Ratio",
    "MA252",
    "MA252_Ratio"
]].tail()

,Close,MA20,MA20_Ratio,MA50,MA50_Ratio,MA252,MA252_Ratio
235187,186.40,196.5925,0.948154,206.604,0.902209,193.260516,0.964501
235188,188.15,195.7400,0.961224,206.052,0.913119,193.381944,0.972945
235189,189.10,195.3900,0.967808,205.489,0.920244,193.556349,0.976976
235190,186.55,194.7200,0.958042,204.918,0.910364,193.702381,0.963075
235191,185.60,193.9525,0.956935,204.380,0.908112,193.833929,0.957521

In [ ]:
master_df["Future_Close_63"] = (
    master_df.groupby("Company")["Close"]
    .shift(-63)
)

master_df["Future_Close_126"] = (
    master_df.groupby("Company")["Close"]
    .shift(-126)
)

master_df["Future_Close_252"] = (
    master_df.groupby("Company")["Close"]
    .shift(-252)
)

In [ ]:
master_df["Future_Return_63"] = (
    (master_df["Future_Close_63"] - master_df["Close"])
    / master_df["Close"]
) * 100

master_df["Future_Return_126"] = (
    (master_df["Future_Close_126"] - master_df["Close"])
    / master_df["Close"]
) * 100

master_df["Future_Return_252"] = (
    (master_df["Future_Close_252"] - master_df["Close"])
    / master_df["Close"]
) * 100

In [ ]:
master_df["Future_Close_630"] = (
    master_df.groupby("Company")["Close"].shift(-630)
)

master_df["Future_Close_1260"] = (
    master_df.groupby("Company")["Close"].shift(-1260)
)

In [ ]:
master_df["Future_Return_630"] = (
    (master_df["Future_Close_630"] - master_df["Close"])
    / master_df["Close"]
) * 100

master_df["Future_Return_1260"] = (
    (master_df["Future_Close_1260"] - master_df["Close"])
    / master_df["Close"]
) * 100

In [ ]:
master_df[[
    "Company",
    "Date",
    "Close",
    "Future_Return_63",
    "Future_Return_126",
    "Future_Return_252",
    "Future_Return_630",
    "Future_Return_1260"
]].tail()

,Company,Date,Close,Future_Return_63,Future_Return_126,Future_Return_252,Future_Return_630,Future_Return_1260
235187,ZEEL,2021-04-26,186.40,NaN,NaN,NaN,NaN,NaN
235188,ZEEL,2021-04-27,188.15,NaN,NaN,NaN,NaN,NaN
235189,ZEEL,2021-04-28,189.10,NaN,NaN,NaN,NaN,NaN
235190,ZEEL,2021-04-29,186.55,NaN,NaN,NaN,NaN,NaN
235191,ZEEL,2021-04-30,185.60,NaN,NaN,NaN,NaN,NaN

In [ ]:
master_df[[
    "Momentum_5",
    "MA20",
    "MA50",
    "MA252",
    "MA20_Ratio",
    "MA50_Ratio",
    "MA252_Ratio",
    "Future_Return_63",
    "Future_Return_126",
    "Future_Return_252",
    "Future_Return_630",
    "Future_Return_1260"
]].isnull().sum()

Momentum_5              245
MA20                    931
MA50                   2401
MA252                 12299
MA20_Ratio              931
MA50_Ratio             2401
MA252_Ratio           12299
Future_Return_63       3087
Future_Return_126      6174
Future_Return_252     12348
Future_Return_630     30870
Future_Return_1260    61740
dtype: int64

In [ ]:
model_df = master_df.copy()

model_df = model_df.dropna(
    subset=[
        "Momentum_5",
        "MA20",
        "MA50",
        "MA252",
        "MA20_Ratio",
        "MA50_Ratio",
        "MA252_Ratio",
        "Future_Return_63",
        "Future_Return_126",
        "Future_Return_252",
        "Future_Return_630",
        "Future_Return_1260"
    ]
)

In [ ]:
print(model_df.shape)

(161153, 30)

In [ ]:
print(model_df.isnull().sum().sum())

0

In [ ]:
model_df = model_df.sort_values(["Company", "Date"]).reset_index(drop=True)

In [ ]:
features = [
    "Prev Close",
    "Open",
    "High",
    "Low",
    "Close",
    "VWAP",
    "Volume",
    "Turnover",
    "Daily_Return",
    "Volatility",
    "Momentum_5",
    "MA20_Ratio",
    "MA50_Ratio",
    "MA252_Ratio"
]

target_cols = [
    "Future_Return_63",
    "Future_Return_126",
    "Future_Return_252",
    "Future_Return_630",
    "Future_Return_1260"
]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import joblib

In [ ]:
BASE_DIR = "/content"   # or your working dir

os.makedirs(f"{BASE_DIR}/models", exist_ok=True)
os.makedirs(f"{BASE_DIR}/scalers", exist_ok=True)

In [ ]:
latest_features = (
    model_df
    .sort_values(["Company", "Date"])
    .groupby("Company")
    .tail(1)
)

latest_features.to_csv(
    "latest_features.csv",
    index=False
)

print(latest_features.shape)

(49, 30)

In [ ]:
import tensorflow as tf
import keras

In [ ]:
for company in model_df["Company"].unique():

    print(f"\nProcessing {company}")

    df = model_df[model_df["Company"] == company].copy()
    df = df.dropna(subset=features + target_cols)

    if len(df) < 500:
        print(f"Skipping {company} (not enough data)")
        continue

    X = df[features]
    y = df[target_cols]

    split = int(len(df) * 0.8)

    X_train = X.iloc[:split]
    X_test = X.iloc[split:]

    y_train = y.iloc[:split]
    y_test = y.iloc[split:]

    scaler = StandardScaler()

    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(5)
    ])

    model.compile(optimizer='adam', loss='mse', metrics=['mae'])

    model.fit(
    X_train_scaled,
    y_train,
    validation_data=(X_test_scaled, y_test),
    epochs=15,
    batch_size=32
    )

    model.evaluate(X_test_scaled, y_test)

    model.save(f"{BASE_DIR}/models/{company}_model.keras")
    joblib.dump(scaler, f"{BASE_DIR}/scalers/{company}_scaler.pkl")

Processing ADANIPORTS
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5392.1514 - mae: 52.4646 - val_loss: 2392.0229 - val_mae: 28.5159
Epoch 2/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4922.3042 - mae: 50.3703 - val_loss: 2147.9287 - val_mae: 27.9731
Epoch 3/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3352.9778 - mae: 41.2971 - val_loss: 1625.8369 - val_mae: 26.4793
Epoch 4/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2007.6012 - mae: 32.9103 - val_loss: 1475.5793 - val_mae: 25.5113
Epoch 5/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1605.4604 - mae: 30.0780 - val_loss: 1514.2010 - val_mae: 25.1456
Epoch 6/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1423.3206 - mae: 28.7908 - val_loss: 1640.4022 - val_mae: 25.5707
Epoch 7/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1310.7842 - mae: 27.7276 - val_loss: 1754.0822 - val_mae: 26.2434
Epoch 8/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1223.0770 - mae: 26.7214 - val_loss: 1877.1547 - val_mae: 27.0060
Epoch 9/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1155.8542 - mae: 25.7866 - val_loss: 1954.0989 - val_mae: 27.5642
Epoch 10/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1104.6685 - mae: 25.1180 - val_loss: 1970.4961 - val_mae: 27.7355
Epoch 11/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1066.7280 - mae: 24.6131 - val_loss: 1990.5176 - val_mae: 27.8569
Epoch 12/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1027.9951 - mae: 24.0239 - val_loss: 2055.7214 - val_mae: 28.6449
Epoch 13/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 992.3107 - mae: 23.4874 - val_loss: 2093.8379 - val_mae: 28.9025
Epoch 14/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 967.8619 - mae: 23.1428 - val_loss: 2175.7634 - val_mae: 30.0789
Epoch 15/15
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 937.3339 - mae: 22.6744 - val_loss: 2311.7310 - val_mae: 31.6945
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2311.7310 - mae: 31.6945

Processing ASIANPAINT
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 14606.1953 - mae: 71.2739 - val_loss: 3931.5564 - val_mae: 47.1260
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7493.1113 - mae: 56.8354 - val_loss: 4159.2363 - val_mae: 39.2398
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4785.6035 - mae: 45.9075 - val_loss: 19026.8164 - val_mae: 74.3148
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4273.1382 - mae: 43.0835 - val_loss: 34076.2148 - val_mae: 96.7155
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3918.0725 - mae: 40.8949 - val_loss: 45279.6484 - val_mae: 109.1546
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3576.8635 - mae: 38.8037 - val_loss: 47930.7148 - val_mae: 116.7719
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3313.1780 - mae: 37.2786 - val_loss: 56351.8594 - val_mae: 129.2239
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3107.0906 - mae: 36.1967 - val_loss: 55253.3438 - val_mae: 129.1418
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2946.0027 - mae: 35.2857 - val_loss: 58115.8828 - val_mae: 136.9861
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2815.9761 - mae: 34.4530 - val_loss: 55973.2656 - val_mae: 137.2005
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2717.6345 - mae: 33.7861 - val_loss: 59716.7734 - val_mae: 143.7536
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2634.1482 - mae: 33.2174 - val_loss: 60347.8477 - val_mae: 147.7975
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2564.5386 - mae: 32.7371 - val_loss: 64759.0508 - val_mae: 155.9197
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2502.0493 - mae: 32.2471 - val_loss: 65631.6641 - val_mae: 156.2183
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2442.7417 - mae: 31.7625 - val_loss: 63934.3125 - val_mae: 157.4190
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 63934.3125 - mae: 157.4190

Processing AXISBANK
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 124343.0234 - mae: 145.2895 - val_loss: 1685.2400 - val_mae: 33.2299
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 76374.8594 - mae: 105.9601 - val_loss: 6813.8091 - val_mae: 49.4144
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26736.2344 - mae: 75.7511 - val_loss: 7395.3042 - val_mae: 50.5690
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23702.2930 - mae: 73.5959 - val_loss: 6472.3564 - val_mae: 49.8719
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22597.2812 - mae: 71.0758 - val_loss: 7186.8457 - val_mae: 52.8378
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21836.4043 - mae: 69.7546 - val_loss: 7962.4629 - val_mae: 58.1288
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21234.5449 - mae: 68.5827 - val_loss: 8692.4072 - val_mae: 60.1976
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20741.7070 - mae: 68.0425 - val_loss: 8540.4609 - val_mae: 61.2967
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20259.1152 - mae: 67.1831 - val_loss: 8603.8857 - val_mae: 62.9637
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19858.5234 - mae: 66.5156 - val_loss: 9473.8047 - val_mae: 66.3838
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19601.9414 - mae: 65.9605 - val_loss: 10128.9014 - val_mae: 68.5449
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19261.9062 - mae: 65.1701 - val_loss: 10578.2988 - val_mae: 69.8208
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18912.0000 - mae: 64.6543 - val_loss: 11346.3408 - val_mae: 72.7490
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18661.3691 - mae: 64.3857 - val_loss: 11738.4873 - val_mae: 73.9897
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18284.1719 - mae: 63.5051 - val_loss: 13322.0840 - val_mae: 77.6578
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13322.0840 - mae: 77.6578

Processing BAJAJ-AUTO

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 1407.3044 - mae: 27.7134 - val_loss: 501.1161 - val_mae: 17.2163
Epoch 2/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1012.6995 - mae: 23.6984 - val_loss: 369.3478 - val_mae: 14.4135
Epoch 3/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 568.0942 - mae: 18.6106 - val_loss: 347.8777 - val_mae: 14.4125
Epoch 4/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 451.4752 - mae: 16.6174 - val_loss: 384.3904 - val_mae: 15.7442
Epoch 5/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 394.7082 - mae: 15.4607 - val_loss: 368.4438 - val_mae: 15.4979
Epoch 6/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 349.3081 - mae: 14.5416 - val_loss: 353.5431 - val_mae: 14.9994
Epoch 7/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 312.1423 - mae: 13.7462 - val_loss: 341.1673 - val_mae: 14.6447
Epoch 8/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 282.4799 - mae: 13.1081 - val_loss: 337.5907 - val_mae: 14.3108
Epoch 9/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 260.4191 - mae: 12.5894 - val_loss: 323.7698 - val_mae: 13.9248
Epoch 10/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 244.9834 - mae: 12.1870 - val_loss: 317.1368 - val_mae: 13.8202
Epoch 11/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 232.4483 - mae: 11.8688 - val_loss: 291.2847 - val_mae: 13.1793
Epoch 12/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 222.8412 - mae: 11.6158 - val_loss: 275.1637 - val_mae: 12.6232
Epoch 13/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 215.0280 - mae: 11.4500 - val_loss: 271.6570 - val_mae: 12.5601
Epoch 14/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 208.8508 - mae: 11.2685 - val_loss: 278.9575 - val_mae: 13.0320
Epoch 15/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 202.6250 - mae: 11.1021 - val_loss: 266.2663 - val_mae: 12.7359
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 266.2663 - mae: 12.7359

Processing BAJAJFINSV
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 71120.7734 - mae: 146.6658 - val_loss: 42992.8906 - val_mae: 136.4852
Epoch 2/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 68961.0156 - mae: 143.2929 - val_loss: 26896.2520 - val_mae: 108.7555
Epoch 3/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57905.1250 - mae: 126.9493 - val_loss: 47889.1719 - val_mae: 185.1708
Epoch 4/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 33816.2422 - mae: 93.8796 - val_loss: 505854.5312 - val_mae: 471.0362
Epoch 5/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17392.0254 - mae: 70.1065 - val_loss: 837729.8125 - val_mae: 510.2266
Epoch 6/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11856.0049 - mae: 60.3322 - val_loss: 791942.0000 - val_mae: 479.2567
Epoch 7/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9082.7734 - mae: 54.9570 - val_loss: 682105.6875 - val_mae: 441.3385
Epoch 8/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7550.9282 - mae: 51.4693 - val_loss: 555813.0000 - val_mae: 387.5053
Epoch 9/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6708.6973 - mae: 49.2632 - val_loss: 520195.1250 - val_mae: 374.3355
Epoch 10/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6184.0791 - mae: 47.9457 - val_loss: 491935.1875 - val_mae: 358.8952
Epoch 11/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5801.5566 - mae: 46.7819 - val_loss: 452786.5938 - val_mae: 345.4283
Epoch 12/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5531.4292 - mae: 46.1791 - val_loss: 464843.3125 - val_mae: 349.8055
Epoch 13/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5297.2817 - mae: 45.5833 - val_loss: 441449.5000 - val_mae: 341.5192
Epoch 14/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5115.1182 - mae: 45.0177 - val_loss: 441447.8438 - val_mae: 344.3296
Epoch 15/15
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4956.2231 - mae: 44.7786 - val_loss: 389998.6875 - val_mae: 317.3572
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 389998.6875 - mae: 317.3572

Processing BAJFINANCE
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 150967.1875 - mae: 182.5029 - val_loss: 30078.5859 - val_mae: 129.2077
Epoch 2/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 110497.6250 - mae: 156.3870 - val_loss: 555349.7500 - val_mae: 462.1638
Epoch 3/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 71847.2891 - mae: 138.4022 - val_loss: 478273.7500 - val_mae: 393.2730
Epoch 4/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 66379.8203 - mae: 135.8994 - val_loss: 492981.8750 - val_mae: 398.2307
Epoch 5/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 63848.9961 - mae: 135.6947 - val_loss: 400836.7188 - val_mae: 359.9326
Epoch 6/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 61389.2539 - mae: 134.4268 - val_loss: 336614.0625 - val_mae: 334.4015
Epoch 7/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 58824.7344 - mae: 133.6039 - val_loss: 318987.9688 - val_mae: 326.9597
Epoch 8/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56025.7500 - mae: 132.6270 - val_loss: 272674.6250 - val_mae: 305.1339
Epoch 9/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53376.3438 - mae: 130.8954 - val_loss: 248937.5625 - val_mae: 291.6143
Epoch 10/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50701.8984 - mae: 129.4748 - val_loss: 229337.3281 - val_mae: 281.7310
Epoch 11/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48419.0977 - mae: 127.7251 - val_loss: 189271.7031 - val_mae: 259.3514
Epoch 12/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 46247.7656 - mae: 124.9662 - val_loss: 197436.0938 - val_mae: 263.7029
Epoch 13/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 44399.6172 - mae: 123.4485 - val_loss: 122835.6484 - val_mae: 213.6897
Epoch 14/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 42824.4414 - mae: 121.0792 - val_loss: 143779.2656 - val_mae: 226.4629
Epoch 15/15
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 41727.4023 - mae: 119.3226 - val_loss: 112152.4531 - val_mae: 203.8766
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 112152.4531 - mae: 203.8766

Processing BHARTIARTL
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

82/82 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 69842.4766 - mae: 85.1144 - val_loss: 358.6555 - val_mae: 13.9409
Epoch 2/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55571.1953 - mae: 74.2336 - val_loss: 1753.0361 - val_mae: 32.0346
Epoch 3/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32960.2188 - mae: 68.8080 - val_loss: 2399.6228 - val_mae: 30.7698
Epoch 4/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26856.0430 - mae: 62.7762 - val_loss: 1169.2125 - val_mae: 23.1150
Epoch 5/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22694.5742 - mae: 56.6446 - val_loss: 1188.4155 - val_mae: 23.8662
Epoch 6/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19079.0371 - mae: 54.3683 - val_loss: 1132.5294 - val_mae: 23.4373
Epoch 7/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16105.8701 - mae: 51.4066 - val_loss: 1349.4497 - val_mae: 25.2705
Epoch 8/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13350.4365 - mae: 48.4865 - val_loss: 1144.2308 - val_mae: 23.2033
Epoch 9/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11324.2871 - mae: 46.8262 - val_loss: 1051.8864 - val_mae: 21.9869
Epoch 10/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9681.5566 - mae: 45.1916 - val_loss: 979.3115 - val_mae: 20.9031
Epoch 11/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8626.8096 - mae: 44.1146 - val_loss: 847.0537 - val_mae: 19.5456
Epoch 12/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7738.3755 - mae: 42.9523 - val_loss: 757.4583 - val_mae: 18.6229
Epoch 13/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7052.0649 - mae: 41.8704 - val_loss: 759.9288 - val_mae: 18.4871
Epoch 14/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6498.5366 - mae: 41.0334 - val_loss: 726.8160 - val_mae: 18.1721
Epoch 15/15
82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5933.8774 - mae: 40.0936 - val_loss: 737.8073 - val_mae: 18.3730
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 737.8073 - mae: 18.3730

Processing BPCL
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2055.4009 - mae: 32.1620 - val_loss: 2620.2009 - val_mae: 36.6113
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1064.7076 - mae: 25.5747 - val_loss: 2506.7261 - val_mae: 39.4287
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 853.6505 - mae: 23.4763 - val_loss: 2479.0776 - val_mae: 38.6094
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 836.6375 - mae: 23.2528 - val_loss: 2478.4880 - val_mae: 38.7229
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 826.2213 - mae: 23.1031 - val_loss: 2373.5278 - val_mae: 38.1078
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 814.6807 - mae: 22.9322 - val_loss: 2359.3171 - val_mae: 37.8991
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 805.9445 - mae: 22.7881 - val_loss: 2275.1226 - val_mae: 37.0680
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 797.3950 - mae: 22.6578 - val_loss: 2276.4287 - val_mae: 37.3525
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 789.1610 - mae: 22.5094 - val_loss: 2214.4180 - val_mae: 37.1714
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 779.7601 - mae: 22.3646 - val_loss: 2233.1797 - val_mae: 37.9713
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 771.2097 - mae: 22.2148 - val_loss: 2176.9080 - val_mae: 37.4518
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 759.0429 - mae: 22.0586 - val_loss: 2181.5447 - val_mae: 37.9574
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 746.9771 - mae: 21.8428 - val_loss: 2219.9814 - val_mae: 39.2144
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 733.9588 - mae: 21.6423 - val_loss: 2173.0085 - val_mae: 38.5999
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 720.1669 - mae: 21.3820 - val_loss: 2162.8486 - val_mae: 38.1983
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2162.8486 - mae: 38.1983

Processing BRITANNIA
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 22762.5117 - mae: 69.0463 - val_loss: 37586.7109 - val_mae: 106.8653
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10612.5371 - mae: 52.2268 - val_loss: 25170.2949 - val_mae: 108.4446
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6846.1777 - mae: 47.5316 - val_loss: 25120.2793 - val_mae: 112.5345
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6672.2866 - mae: 46.8801 - val_loss: 26521.9453 - val_mae: 117.5490
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6550.7817 - mae: 46.7504 - val_loss: 26766.2344 - val_mae: 119.8016
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6459.9194 - mae: 46.5240 - val_loss: 28592.1660 - val_mae: 124.7346
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6347.4399 - mae: 46.0915 - val_loss: 29233.5762 - val_mae: 127.1474
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6221.2617 - mae: 45.6749 - val_loss: 29679.4395 - val_mae: 128.5475
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6072.5376 - mae: 45.6770 - val_loss: 31378.8770 - val_mae: 132.5678
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5926.7505 - mae: 45.0610 - val_loss: 31277.5938 - val_mae: 132.5141
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5751.1704 - mae: 44.4681 - val_loss: 30352.5000 - val_mae: 130.4662
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5597.2900 - mae: 43.9257 - val_loss: 29368.1113 - val_mae: 127.3857
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5471.2847 - mae: 43.2520 - val_loss: 31235.2051 - val_mae: 130.6822
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5198.4521 - mae: 42.5917 - val_loss: 28581.9863 - val_mae: 125.8516
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4978.5151 - mae: 41.6259 - val_loss: 28290.2969 - val_mae: 123.7771
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28290.2969 - mae: 123.7771

Processing CIPLA
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2068.6272 - mae: 33.8568 - val_loss: 690.0240 - val_mae: 19.8709
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1128.5259 - mae: 26.0092 - val_loss: 564.7307 - val_mae: 17.0657
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 878.4327 - mae: 22.4448 - val_loss: 632.0067 - val_mae: 18.0567
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 822.9610 - mae: 21.6559 - val_loss: 671.7369 - val_mae: 18.5860
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 801.2305 - mae: 21.4017 - val_loss: 663.0302 - val_mae: 18.5783
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 782.0797 - mae: 21.0697 - val_loss: 670.9797 - val_mae: 18.7481
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 761.9903 - mae: 20.8194 - val_loss: 692.7178 - val_mae: 19.2713
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 740.5040 - mae: 20.4628 - val_loss: 711.8953 - val_mae: 19.5715
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 718.5483 - mae: 20.0522 - val_loss: 696.9429 - val_mae: 19.5357
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 698.1430 - mae: 19.7308 - val_loss: 743.0656 - val_mae: 20.2780
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 674.1052 - mae: 19.3454 - val_loss: 781.3979 - val_mae: 20.8391
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 655.2726 - mae: 19.0084 - val_loss: 765.2328 - val_mae: 20.8196
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 638.7847 - mae: 18.7682 - val_loss: 793.6312 - val_mae: 21.1540
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 625.4308 - mae: 18.6367 - val_loss: 796.2708 - val_mae: 21.3863
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 615.8076 - mae: 18.4187 - val_loss: 819.0783 - val_mae: 21.6587
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 819.0783 - mae: 21.6587

Processing COALINDIA
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 422.3163 - mae: 15.5029 - val_loss: 919.9974 - val_mae: 22.3023
Epoch 2/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 383.4866 - mae: 14.8416 - val_loss: 801.5255 - val_mae: 21.2387
Epoch 3/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 284.1880 - mae: 13.0615 - val_loss: 565.0688 - val_mae: 18.5482
Epoch 4/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 182.6451 - mae: 10.9541 - val_loss: 487.0154 - val_mae: 17.1657
Epoch 5/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 158.1408 - mae: 10.2287 - val_loss: 463.5475 - val_mae: 16.3858
Epoch 6/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 147.7149 - mae: 9.7765 - val_loss: 442.6861 - val_mae: 15.8615
Epoch 7/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 141.8568 - mae: 9.5347 - val_loss: 417.9967 - val_mae: 15.3538
Epoch 8/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 138.4029 - mae: 9.3799 - val_loss: 418.9139 - val_mae: 15.4461
Epoch 9/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 135.0562 - mae: 9.2535 - val_loss: 407.1828 - val_mae: 15.2179
Epoch 10/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 132.0305 - mae: 9.1715 - val_loss: 386.7799 - val_mae: 14.6728
Epoch 11/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 128.9130 - mae: 9.0485 - val_loss: 389.6120 - val_mae: 14.7389
Epoch 12/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 126.4580 - mae: 8.9638 - val_loss: 383.8156 - val_mae: 14.6190
Epoch 13/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 123.7409 - mae: 8.8578 - val_loss: 376.1469 - val_mae: 14.4451
Epoch 14/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 120.5396 - mae: 8.7323 - val_loss: 389.6263 - val_mae: 14.8362
Epoch 15/15
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 117.6752 - mae: 8.6320 - val_loss: 386.1587 - val_mae: 14.7915
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 386.1587 - mae: 14.7915

Processing DRREDDY
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 7018.2998 - mae: 48.5565 - val_loss: 709.9681 - val_mae: 19.9305
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4476.7427 - mae: 43.5009 - val_loss: 11235.1250 - val_mae: 71.0415
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2680.3044 - mae: 37.2060 - val_loss: 13960.0918 - val_mae: 78.3266
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2320.9497 - mae: 34.4419 - val_loss: 18677.3047 - val_mae: 90.0318
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2042.0475 - mae: 32.2162 - val_loss: 16697.8555 - val_mae: 85.7057
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1819.1591 - mae: 30.2609 - val_loss: 17843.4590 - val_mae: 88.5465
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1666.8055 - mae: 29.0049 - val_loss: 17159.9180 - val_mae: 87.4984
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1562.4840 - mae: 28.0789 - val_loss: 20141.6250 - val_mae: 93.8908
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1477.7745 - mae: 27.4222 - val_loss: 16266.3740 - val_mae: 84.7583
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1402.0779 - mae: 26.7716 - val_loss: 18041.4141 - val_mae: 89.0374
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1338.4126 - mae: 26.2539 - val_loss: 15860.7783 - val_mae: 83.1467
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1287.1577 - mae: 25.7470 - val_loss: 16000.1406 - val_mae: 83.8547
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1234.7487 - mae: 25.3003 - val_loss: 14914.1504 - val_mae: 80.4478
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1186.2081 - mae: 24.7872 - val_loss: 16824.5273 - val_mae: 85.0482
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1144.4150 - mae: 24.3417 - val_loss: 15307.7949 - val_mae: 81.4957
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15307.7949 - mae: 81.4957

Processing EICHERMOT
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 329561.0938 - mae: 270.9131 - val_loss: 241782.5469 - val_mae: 366.3563
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 242644.3281 - mae: 225.1744 - val_loss: 29261810.0000 - val_mae: 2849.7854
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 152515.2969 - mae: 178.2353 - val_loss: 28253616.0000 - val_mae: 2722.6162
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 143985.5156 - mae: 177.5377 - val_loss: 25789586.0000 - val_mae: 2563.4309
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 137192.4062 - mae: 174.7534 - val_loss: 22040570.0000 - val_mae: 2346.1653
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 130842.4141 - mae: 172.4207 - val_loss: 20979954.0000 - val_mae: 2276.0938
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 125283.3672 - mae: 170.5614 - val_loss: 18941632.0000 - val_mae: 2140.8699
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 120574.7031 - mae: 168.1273 - val_loss: 18365978.0000 - val_mae: 2089.1284
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 116995.4688 - mae: 167.2769 - val_loss: 17172202.0000 - val_mae: 2017.9619
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 113982.9766 - mae: 165.7961 - val_loss: 16635965.0000 - val_mae: 1951.9332
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 111943.7812 - mae: 163.7095 - val_loss: 15954150.0000 - val_mae: 1903.1935
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 109661.8359 - mae: 162.3965 - val_loss: 17853422.0000 - val_mae: 2016.1803
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 107945.2891 - mae: 161.3739 - val_loss: 16450294.0000 - val_mae: 1917.2307
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 105444.7422 - mae: 159.2667 - val_loss: 17259792.0000 - val_mae: 1938.2571
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 102518.1094 - mae: 157.4754 - val_loss: 15895117.0000 - val_mae: 1846.1918
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15895117.0000 - mae: 1846.1918

Processing GAIL
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

87/87 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6873.7969 - mae: 41.7078 - val_loss: 1006.9269 - val_mae: 22.3682
Epoch 2/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3018.3574 - mae: 30.6224 - val_loss: 1133.5991 - val_mae: 22.2471
Epoch 3/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1189.9934 - mae: 23.2884 - val_loss: 1025.8204 - val_mae: 21.6288
Epoch 4/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1095.1250 - mae: 22.1158 - val_loss: 951.5496 - val_mae: 20.9101
Epoch 5/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1037.5657 - mae: 21.6060 - val_loss: 916.1644 - val_mae: 20.3285
Epoch 6/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 989.6226 - mae: 21.1611 - val_loss: 903.3007 - val_mae: 19.9010
Epoch 7/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 946.5107 - mae: 20.7690 - val_loss: 886.8691 - val_mae: 19.5552
Epoch 8/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 903.3843 - mae: 20.3761 - val_loss: 882.6567 - val_mae: 19.3479
Epoch 9/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 860.8875 - mae: 19.9259 - val_loss: 881.1668 - val_mae: 19.2642
Epoch 10/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 816.4877 - mae: 19.5479 - val_loss: 886.1423 - val_mae: 19.3392
Epoch 11/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 779.9305 - mae: 19.2022 - val_loss: 865.6371 - val_mae: 19.2110
Epoch 12/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 743.7970 - mae: 18.8276 - val_loss: 868.8361 - val_mae: 19.3071
Epoch 13/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 714.9767 - mae: 18.5106 - val_loss: 893.7949 - val_mae: 19.5816
Epoch 14/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 680.0074 - mae: 18.2100 - val_loss: 846.1656 - val_mae: 19.2788
Epoch 15/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 648.4642 - mae: 17.8358 - val_loss: 857.1085 - val_mae: 19.4671
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 857.1085 - mae: 19.4671

Processing GRASIM
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 28919.5000 - mae: 75.0787 - val_loss: 2360.6550 - val_mae: 37.7062
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14879.0010 - mae: 55.4750 - val_loss: 2281.8474 - val_mae: 38.3260
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4736.6484 - mae: 40.9714 - val_loss: 2201.7112 - val_mae: 38.4561
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4355.7852 - mae: 40.1047 - val_loss: 2147.0164 - val_mae: 37.9710
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4141.2104 - mae: 39.7331 - val_loss: 2065.5071 - val_mae: 37.3371
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3919.8943 - mae: 39.1814 - val_loss: 2026.5748 - val_mae: 36.3873
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3706.1367 - mae: 38.4002 - val_loss: 2051.0928 - val_mae: 36.3705
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3451.1975 - mae: 37.0682 - val_loss: 2159.1279 - val_mae: 38.7321
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3185.0754 - mae: 35.5871 - val_loss: 2096.8044 - val_mae: 39.3581
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2958.3152 - mae: 34.3424 - val_loss: 2049.8406 - val_mae: 39.5205
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2715.2959 - mae: 33.2186 - val_loss: 1977.0665 - val_mae: 38.0428
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2546.5742 - mae: 32.2948 - val_loss: 1948.4025 - val_mae: 38.1578
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2411.3718 - mae: 31.6569 - val_loss: 1853.2288 - val_mae: 37.1661
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2320.6257 - mae: 31.0790 - val_loss: 1916.6555 - val_mae: 37.6277
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2247.6484 - mae: 30.7420 - val_loss: 1785.9395 - val_mae: 36.9843
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1785.9395 - mae: 36.9843

Processing HCLTECH
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 19491.6602 - mae: 67.1352 - val_loss: 2844.1746 - val_mae: 40.6560
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14256.8643 - mae: 60.3583 - val_loss: 4524.0293 - val_mae: 49.7343
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10532.4023 - mae: 58.4173 - val_loss: 4043.5676 - val_mae: 45.3504
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10098.1484 - mae: 57.3061 - val_loss: 2256.9597 - val_mae: 34.3041
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9725.8262 - mae: 55.4155 - val_loss: 3023.1121 - val_mae: 42.2879
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9344.8027 - mae: 53.7935 - val_loss: 4145.1592 - val_mae: 49.3121
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9049.3525 - mae: 52.8983 - val_loss: 5044.6870 - val_mae: 54.2808
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8812.4131 - mae: 52.1950 - val_loss: 6679.8027 - val_mae: 66.4891
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8554.5449 - mae: 51.6057 - val_loss: 6293.2275 - val_mae: 64.1548
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8332.8838 - mae: 51.2866 - val_loss: 5735.7051 - val_mae: 61.6033
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8116.8789 - mae: 50.5536 - val_loss: 5909.3887 - val_mae: 63.6973
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7868.8359 - mae: 50.0619 - val_loss: 5766.5596 - val_mae: 64.5558
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7613.6558 - mae: 49.4375 - val_loss: 5840.3857 - val_mae: 65.4630
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7372.1152 - mae: 48.8128 - val_loss: 4937.2642 - val_mae: 60.0778
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7142.2295 - mae: 48.3240 - val_loss: 5027.9692 - val_mae: 60.7423
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5027.9692 - mae: 60.7423

Processing HDFC
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9995.0742 - mae: 57.0532 - val_loss: 2375.4700 - val_mae: 33.2021
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4969.6118 - mae: 45.8341 - val_loss: 1299.4207 - val_mae: 24.9314
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3416.5701 - mae: 39.5966 - val_loss: 1973.6443 - val_mae: 30.3413
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3190.4871 - mae: 38.3177 - val_loss: 2217.2517 - val_mae: 31.9517
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3020.3367 - mae: 37.6443 - val_loss: 2300.3083 - val_mae: 32.2800
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2863.6653 - mae: 37.0691 - val_loss: 2434.2078 - val_mae: 33.3012
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2714.1497 - mae: 36.3194 - val_loss: 2403.5386 - val_mae: 32.8540
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2562.9104 - mae: 35.4521 - val_loss: 2407.1667 - val_mae: 32.5049
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2414.6484 - mae: 34.4477 - val_loss: 2397.7661 - val_mae: 32.3813
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2287.7625 - mae: 33.4605 - val_loss: 2348.7800 - val_mae: 31.7750
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2180.6882 - mae: 32.5457 - val_loss: 2312.8530 - val_mae: 31.4270
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2085.1545 - mae: 31.6908 - val_loss: 2245.9314 - val_mae: 30.9586
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2001.4984 - mae: 30.8919 - val_loss: 2241.0881 - val_mae: 31.0715
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1924.2942 - mae: 30.1589 - val_loss: 2170.0242 - val_mae: 30.4783
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1856.8228 - mae: 29.4770 - val_loss: 2155.7573 - val_mae: 30.5837
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2155.7573 - mae: 30.5837

Processing HDFCBANK
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 13302.3389 - mae: 66.6852 - val_loss: 4588.4570 - val_mae: 39.9865
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4920.6543 - mae: 44.6735 - val_loss: 2378.8950 - val_mae: 32.4061
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2655.5332 - mae: 34.7452 - val_loss: 2075.6309 - val_mae: 31.2152
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2525.5603 - mae: 33.2085 - val_loss: 1875.5645 - val_mae: 29.4151
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2474.1733 - mae: 32.6414 - val_loss: 1706.1127 - val_mae: 27.7831
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2433.4941 - mae: 32.2556 - val_loss: 1584.8242 - val_mae: 26.5910
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2379.3909 - mae: 31.7683 - val_loss: 1454.9584 - val_mae: 25.4721
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2329.6262 - mae: 31.3200 - val_loss: 1400.6150 - val_mae: 25.0272
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2264.0791 - mae: 30.5609 - val_loss: 1300.3129 - val_mae: 24.2133
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2203.0908 - mae: 29.8388 - val_loss: 1201.7545 - val_mae: 23.6777
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2139.2383 - mae: 29.1252 - val_loss: 1123.9032 - val_mae: 23.4597
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2093.1208 - mae: 28.5452 - val_loss: 1086.5836 - val_mae: 23.4769
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2045.0425 - mae: 28.0728 - val_loss: 1143.2233 - val_mae: 24.4550
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2010.2721 - mae: 27.7098 - val_loss: 1030.3269 - val_mae: 23.4926
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1984.8141 - mae: 27.5438 - val_loss: 1043.9998 - val_mae: 23.7694
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1043.9998 - mae: 23.7694

Processing HEROMOTOCO
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8104.7861 - mae: 56.8018 - val_loss: 1060.0356 - val_mae: 23.3251
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2749.7566 - mae: 36.5983 - val_loss: 2036.5912 - val_mae: 29.5524
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1874.1859 - mae: 32.0143 - val_loss: 2087.8533 - val_mae: 29.8785
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1775.7103 - mae: 31.2248 - val_loss: 1956.0236 - val_mae: 29.4615
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1696.8599 - mae: 30.4852 - val_loss: 1740.8793 - val_mae: 28.6879
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1639.0247 - mae: 29.7683 - val_loss: 1624.7451 - val_mae: 27.9595
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1582.5619 - mae: 29.1408 - val_loss: 1447.1742 - val_mae: 27.3198
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1544.6476 - mae: 28.6918 - val_loss: 1313.9403 - val_mae: 26.7754
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1516.8376 - mae: 28.2531 - val_loss: 1256.4042 - val_mae: 27.0194
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1494.5807 - mae: 27.9372 - val_loss: 1100.3916 - val_mae: 25.9958
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1473.6482 - mae: 27.7169 - val_loss: 1110.4027 - val_mae: 25.7695
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1457.9766 - mae: 27.4656 - val_loss: 1045.9032 - val_mae: 26.1646
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1444.5819 - mae: 27.2304 - val_loss: 1052.6904 - val_mae: 26.5053
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1426.0687 - mae: 27.0756 - val_loss: 1040.3046 - val_mae: 26.5128
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1412.2167 - mae: 26.8149 - val_loss: 1023.8146 - val_mae: 26.7363
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1023.8146 - mae: 26.7363

Processing HINDALCO
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3651.9170 - mae: 43.5192 - val_loss: 6425.1885 - val_mae: 52.2250
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2988.7041 - mae: 40.6104 - val_loss: 4685.3408 - val_mae: 46.5921
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2295.0464 - mae: 35.7914 - val_loss: 3906.3604 - val_mae: 44.2138
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1968.4670 - mae: 33.4740 - val_loss: 4085.7256 - val_mae: 45.1652
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1688.7911 - mae: 30.9735 - val_loss: 3467.2285 - val_mae: 42.0237
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1481.4023 - mae: 28.5937 - val_loss: 3106.9907 - val_mae: 39.8504
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1348.1433 - mae: 26.9873 - val_loss: 3066.9690 - val_mae: 39.4058
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1257.8501 - mae: 25.8559 - val_loss: 2905.2698 - val_mae: 38.3081
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1196.7595 - mae: 25.2092 - val_loss: 2487.5688 - val_mae: 35.7105
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1149.1044 - mae: 24.7893 - val_loss: 2536.1653 - val_mae: 35.8130
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1109.3447 - mae: 24.4226 - val_loss: 2471.3916 - val_mae: 35.1302
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1081.0403 - mae: 24.1179 - val_loss: 2355.0884 - val_mae: 34.6659
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1055.8899 - mae: 23.8851 - val_loss: 2408.9160 - val_mae: 34.7042
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1037.5482 - mae: 23.7073 - val_loss: 2441.2112 - val_mae: 34.8283
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1019.8616 - mae: 23.5048 - val_loss: 2375.1929 - val_mae: 34.4438
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2375.1929 - mae: 34.4438

Processing HINDUNILVR
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3657.5645 - mae: 37.0524 - val_loss: 10026.7559 - val_mae: 76.2951
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2105.6333 - mae: 28.5865 - val_loss: 9613.6025 - val_mae: 63.3295
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1735.1703 - mae: 27.2966 - val_loss: 8787.4854 - val_mae: 60.9594
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1558.1146 - mae: 26.6996 - val_loss: 5391.0547 - val_mae: 48.1941
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1468.1089 - mae: 26.2659 - val_loss: 4886.4751 - val_mae: 45.7600
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1403.9779 - mae: 25.8562 - val_loss: 3004.1660 - val_mae: 36.6518
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1320.3822 - mae: 25.2657 - val_loss: 3475.4734 - val_mae: 39.4018
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1229.9133 - mae: 24.5402 - val_loss: 3278.5359 - val_mae: 38.2640
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1140.1677 - mae: 23.7458 - val_loss: 3844.0261 - val_mae: 42.1911
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1069.1495 - mae: 23.0356 - val_loss: 2946.9041 - val_mae: 37.5483
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1013.7936 - mae: 22.3916 - val_loss: 2775.3748 - val_mae: 37.0446
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 969.2405 - mae: 21.8836 - val_loss: 3493.1943 - val_mae: 42.0846
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 922.7385 - mae: 21.2575 - val_loss: 3343.3677 - val_mae: 41.5547
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 883.0041 - mae: 20.8254 - val_loss: 3568.5383 - val_mae: 43.2411
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 848.1494 - mae: 20.3158 - val_loss: 2605.5955 - val_mae: 37.9860
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2605.5955 - mae: 37.9860

Processing ICICIBANK
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19857.8027 - mae: 70.6920 - val_loss: 2796.2871 - val_mae: 43.5524
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8291.7246 - mae: 50.5784 - val_loss: 10155.9785 - val_mae: 69.1009
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4486.9956 - mae: 42.0933 - val_loss: 13241.0439 - val_mae: 73.7923
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4301.7534 - mae: 41.4188 - val_loss: 16653.3340 - val_mae: 82.1155
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4187.6670 - mae: 40.9998 - val_loss: 14272.6768 - val_mae: 78.4267
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4077.8940 - mae: 40.2328 - val_loss: 14927.9502 - val_mae: 82.0348
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3971.3442 - mae: 39.5065 - val_loss: 15788.5537 - val_mae: 85.2397
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3897.0303 - mae: 39.0663 - val_loss: 16517.2441 - val_mae: 88.9775
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3839.8528 - mae: 38.5916 - val_loss: 15633.6689 - val_mae: 87.3312
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3770.1951 - mae: 38.0723 - val_loss: 16943.6777 - val_mae: 90.0380
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3749.3215 - mae: 37.7669 - val_loss: 14610.8799 - val_mae: 87.2557
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3685.7073 - mae: 37.1432 - val_loss: 16772.6172 - val_mae: 91.0847
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3636.5593 - mae: 36.7541 - val_loss: 15507.8936 - val_mae: 88.0093
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3590.0820 - mae: 36.3912 - val_loss: 17632.7344 - val_mae: 92.4835
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3546.2180 - mae: 35.9967 - val_loss: 17581.9824 - val_mae: 93.2766
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17581.9824 - mae: 93.2766

Processing INDUSINDBK
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

87/87 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 54008.3672 - mae: 133.0682 - val_loss: 9469.3623 - val_mae: 67.2510
Epoch 2/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 41626.5391 - mae: 116.0479 - val_loss: 139432.2344 - val_mae: 239.3425
Epoch 3/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18217.7324 - mae: 82.8687 - val_loss: 153466.7500 - val_mae: 215.7558
Epoch 4/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15474.2256 - mae: 76.8542 - val_loss: 138049.7656 - val_mae: 203.7069
Epoch 5/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14402.3105 - mae: 75.1222 - val_loss: 118535.7344 - val_mae: 182.9945
Epoch 6/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13399.8018 - mae: 72.7160 - val_loss: 111594.5547 - val_mae: 178.4772
Epoch 7/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12544.4736 - mae: 71.1692 - val_loss: 104434.6562 - val_mae: 171.6221
Epoch 8/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11829.3838 - mae: 69.3810 - val_loss: 92930.9609 - val_mae: 162.7837
Epoch 9/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11310.7676 - mae: 68.5649 - val_loss: 78856.8984 - val_mae: 147.6785
Epoch 10/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10836.9619 - mae: 67.3450 - val_loss: 71889.1875 - val_mae: 140.7989
Epoch 11/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10529.0918 - mae: 66.7260 - val_loss: 72660.0625 - val_mae: 140.5138
Epoch 12/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10279.1465 - mae: 66.0941 - val_loss: 64744.7930 - val_mae: 131.3412
Epoch 13/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10152.3418 - mae: 65.7652 - val_loss: 68409.6484 - val_mae: 134.9370
Epoch 14/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9967.8457 - mae: 65.3049 - val_loss: 62409.5664 - val_mae: 127.5962
Epoch 15/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9855.5820 - mae: 64.8261 - val_loss: 57256.5742 - val_mae: 121.6773
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57256.5742 - mae: 121.6773

Processing INFY
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1728.4482 - mae: 31.2431 - val_loss: 2180.7754 - val_mae: 39.9860
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1056.2505 - mae: 24.9835 - val_loss: 2543.0640 - val_mae: 43.4957
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 849.7390 - mae: 22.6814 - val_loss: 2503.2395 - val_mae: 42.8972
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 778.4217 - mae: 21.7467 - val_loss: 2470.8191 - val_mae: 42.0467
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 741.6761 - mae: 21.2247 - val_loss: 2675.0298 - val_mae: 42.8068
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 713.6183 - mae: 20.7522 - val_loss: 2652.0769 - val_mae: 41.9637
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 686.1639 - mae: 20.3834 - val_loss: 2771.4800 - val_mae: 42.7322
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 659.1033 - mae: 20.0007 - val_loss: 2933.9663 - val_mae: 43.2052
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 629.7739 - mae: 19.5931 - val_loss: 2998.8896 - val_mae: 42.9669
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 603.3713 - mae: 19.2466 - val_loss: 3002.5679 - val_mae: 42.7679
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 579.1880 - mae: 18.8820 - val_loss: 3067.5276 - val_mae: 43.3635
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 555.8012 - mae: 18.4825 - val_loss: 3216.6631 - val_mae: 43.6515
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 534.4411 - mae: 18.0948 - val_loss: 3713.2009 - val_mae: 46.0668
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 516.4153 - mae: 17.7597 - val_loss: 3686.6360 - val_mae: 45.5564
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 501.7132 - mae: 17.5081 - val_loss: 4027.4302 - val_mae: 47.2667
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4027.4302 - mae: 47.2667

Processing IOC
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3148.2556 - mae: 34.0309 - val_loss: 2009.8240 - val_mae: 34.2033
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1931.2991 - mae: 28.0797 - val_loss: 2946.4404 - val_mae: 37.9614
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 894.0094 - mae: 22.4560 - val_loss: 2706.0596 - val_mae: 35.6340
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 797.7389 - mae: 21.0697 - val_loss: 2542.5344 - val_mae: 35.2015
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 738.9294 - mae: 20.2324 - val_loss: 2411.0388 - val_mae: 34.9997
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 697.2048 - mae: 19.5748 - val_loss: 2539.0479 - val_mae: 35.0702
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 666.9941 - mae: 19.2137 - val_loss: 2574.3193 - val_mae: 35.3139
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 640.2938 - mae: 18.7494 - val_loss: 2674.0002 - val_mae: 35.6100
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 620.6165 - mae: 18.4765 - val_loss: 2550.9863 - val_mae: 35.4993
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 600.4297 - mae: 18.1022 - val_loss: 2669.9790 - val_mae: 36.0566
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 583.8201 - mae: 17.7998 - val_loss: 2750.4749 - val_mae: 36.4331
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 573.3854 - mae: 17.6758 - val_loss: 2742.8464 - val_mae: 36.7503
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 562.4162 - mae: 17.4960 - val_loss: 2763.4875 - val_mae: 36.9819
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 552.0901 - mae: 17.3199 - val_loss: 2805.4375 - val_mae: 37.5252
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 540.5336 - mae: 17.1784 - val_loss: 2868.9312 - val_mae: 37.8125
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2868.9312 - mae: 37.8125

Processing ITC
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2033.1289 - mae: 33.2020 - val_loss: 723.1942 - val_mae: 20.5996
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1318.6656 - mae: 26.4947 - val_loss: 1004.5636 - val_mae: 23.8868
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1242.5084 - mae: 25.9058 - val_loss: 864.6873 - val_mae: 22.2712
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1201.7512 - mae: 25.4851 - val_loss: 692.7795 - val_mae: 19.7156
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1125.5586 - mae: 24.8484 - val_loss: 575.4453 - val_mae: 17.8212
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 975.5139 - mae: 23.4846 - val_loss: 699.5496 - val_mae: 19.6616
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 824.5366 - mae: 21.5984 - val_loss: 673.6286 - val_mae: 19.3888
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 762.0388 - mae: 20.5094 - val_loss: 626.8270 - val_mae: 18.5361
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 731.3646 - mae: 19.9942 - val_loss: 658.9869 - val_mae: 18.8723
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 710.5016 - mae: 19.7008 - val_loss: 647.4998 - val_mae: 18.6574
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 691.4781 - mae: 19.4474 - val_loss: 657.8580 - val_mae: 18.7388
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 671.9730 - mae: 19.1714 - val_loss: 666.4060 - val_mae: 18.8687
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 653.0430 - mae: 18.8838 - val_loss: 635.2595 - val_mae: 18.3433
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 634.7695 - mae: 18.5609 - val_loss: 674.3340 - val_mae: 18.9084
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 618.4412 - mae: 18.2734 - val_loss: 655.0547 - val_mae: 18.7928
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 655.0547 - mae: 18.7928

Processing JSWSTEEL
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8287.2920 - mae: 56.4561 - val_loss: 2984.3879 - val_mae: 45.3738
Epoch 2/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6347.7637 - mae: 49.9332 - val_loss: 2994.3801 - val_mae: 44.9140
Epoch 3/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3262.3945 - mae: 40.3740 - val_loss: 2982.4722 - val_mae: 45.5475
Epoch 4/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2811.1450 - mae: 38.1917 - val_loss: 2982.6931 - val_mae: 45.8934
Epoch 5/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2662.4001 - mae: 37.0356 - val_loss: 2994.2166 - val_mae: 45.6335
Epoch 6/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2542.4297 - mae: 36.1953 - val_loss: 2984.4902 - val_mae: 45.5171
Epoch 7/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2432.6865 - mae: 35.4488 - val_loss: 3003.4883 - val_mae: 45.7507
Epoch 8/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2336.6980 - mae: 34.7305 - val_loss: 2983.5549 - val_mae: 45.2482
Epoch 9/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2256.8071 - mae: 34.1059 - val_loss: 3014.1831 - val_mae: 45.6022
Epoch 10/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2147.0378 - mae: 33.2702 - val_loss: 2986.2822 - val_mae: 45.6880
Epoch 11/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2058.3496 - mae: 32.5868 - val_loss: 2991.8064 - val_mae: 46.1013
Epoch 12/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1985.3168 - mae: 31.9668 - val_loss: 2993.9954 - val_mae: 45.8197
Epoch 13/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1908.6050 - mae: 31.3279 - val_loss: 2941.4226 - val_mae: 45.1844
Epoch 14/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1836.5989 - mae: 30.8133 - val_loss: 2926.1348 - val_mae: 45.3256
Epoch 15/15
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1774.0189 - mae: 30.2481 - val_loss: 2960.3755 - val_mae: 45.5641
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2960.3755 - mae: 45.5641

Processing KOTAKBANK
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

87/87 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8977.8350 - mae: 56.5433 - val_loss: 2849.1780 - val_mae: 37.7819
Epoch 2/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4637.4082 - mae: 45.2463 - val_loss: 2638.9937 - val_mae: 36.6728
Epoch 3/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3689.1169 - mae: 42.2850 - val_loss: 2405.0828 - val_mae: 35.2182
Epoch 4/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3597.1482 - mae: 41.5735 - val_loss: 2135.1816 - val_mae: 32.4828
Epoch 5/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3485.6597 - mae: 40.5847 - val_loss: 1962.0972 - val_mae: 30.8708
Epoch 6/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3395.1509 - mae: 39.4431 - val_loss: 2186.4331 - val_mae: 35.2690
Epoch 7/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3292.4238 - mae: 38.4739 - val_loss: 2332.0779 - val_mae: 36.6104
Epoch 8/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3206.7917 - mae: 37.8254 - val_loss: 2409.6675 - val_mae: 37.6788
Epoch 9/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3139.4592 - mae: 37.1146 - val_loss: 2982.8748 - val_mae: 43.4730
Epoch 10/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3020.9834 - mae: 36.1511 - val_loss: 2966.8003 - val_mae: 43.4297
Epoch 11/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2908.0667 - mae: 35.2499 - val_loss: 3065.0598 - val_mae: 44.2420
Epoch 12/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2791.9924 - mae: 34.3458 - val_loss: 3392.3982 - val_mae: 47.2412
Epoch 13/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2688.7034 - mae: 33.6149 - val_loss: 3719.1323 - val_mae: 49.9260
Epoch 14/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2580.8167 - mae: 32.9604 - val_loss: 3532.7036 - val_mae: 48.3832
Epoch 15/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2492.8574 - mae: 32.5471 - val_loss: 3738.8367 - val_mae: 50.0642
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3738.8367 - mae: 50.0642

Processing LT
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

67/67 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 2428.1008 - mae: 34.9308 - val_loss: 547.3497 - val_mae: 18.8882
Epoch 2/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1822.8531 - mae: 30.5616 - val_loss: 514.0242 - val_mae: 18.2567
Epoch 3/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1225.2996 - mae: 25.0574 - val_loss: 402.0772 - val_mae: 16.1173
Epoch 4/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1077.4354 - mae: 23.3069 - val_loss: 332.2345 - val_mae: 14.6537
Epoch 5/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 993.0350 - mae: 22.0316 - val_loss: 296.7617 - val_mae: 13.8544
Epoch 6/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 941.8513 - mae: 21.4723 - val_loss: 289.1026 - val_mae: 13.6788
Epoch 7/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 906.8367 - mae: 21.1156 - val_loss: 281.0376 - val_mae: 13.4929
Epoch 8/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 880.2892 - mae: 20.8842 - val_loss: 288.9844 - val_mae: 13.6633
Epoch 9/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 856.8201 - mae: 20.6680 - val_loss: 282.1385 - val_mae: 13.4550
Epoch 10/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 834.8569 - mae: 20.5499 - val_loss: 284.3371 - val_mae: 13.4655
Epoch 11/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 810.5355 - mae: 20.3315 - val_loss: 287.1840 - val_mae: 13.4692
Epoch 12/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 788.9618 - mae: 20.1108 - val_loss: 283.9166 - val_mae: 13.3897
Epoch 13/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 764.9982 - mae: 19.8882 - val_loss: 283.3971 - val_mae: 13.3050
Epoch 14/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 735.5569 - mae: 19.6461 - val_loss: 279.1290 - val_mae: 13.2054
Epoch 15/15
67/67 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 712.7078 - mae: 19.3669 - val_loss: 292.5289 - val_mae: 13.3968
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 292.5289 - mae: 13.3968

Processing MARUTI
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

73/73 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 17854.0078 - mae: 74.6368 - val_loss: 6889.9072 - val_mae: 56.9874
Epoch 2/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10984.7256 - mae: 57.3722 - val_loss: 366066.3438 - val_mae: 356.3720
Epoch 3/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5283.1929 - mae: 45.4947 - val_loss: 481861.5938 - val_mae: 361.4862
Epoch 4/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4765.3110 - mae: 44.1740 - val_loss: 544427.0625 - val_mae: 381.3265
Epoch 5/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4484.6587 - mae: 43.2084 - val_loss: 475374.5312 - val_mae: 350.6654
Epoch 6/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4275.3262 - mae: 42.1283 - val_loss: 492760.5625 - val_mae: 347.9861
Epoch 7/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4155.7666 - mae: 41.5444 - val_loss: 462240.0625 - val_mae: 333.7080
Epoch 8/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4071.3022 - mae: 41.1626 - val_loss: 492486.1875 - val_mae: 342.9654
Epoch 9/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4004.9133 - mae: 40.6910 - val_loss: 448368.5625 - val_mae: 323.2787
Epoch 10/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3951.3486 - mae: 40.4290 - val_loss: 392609.6875 - val_mae: 301.5120
Epoch 11/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3915.5669 - mae: 40.2234 - val_loss: 399348.6250 - val_mae: 304.2693
Epoch 12/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3855.2439 - mae: 39.8516 - val_loss: 447887.0625 - val_mae: 323.9998
Epoch 13/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3808.9094 - mae: 39.6025 - val_loss: 429870.8438 - val_mae: 315.8760
Epoch 14/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3756.4546 - mae: 39.2659 - val_loss: 368605.1250 - val_mae: 290.9009
Epoch 15/15
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3713.9314 - mae: 38.9322 - val_loss: 414511.2188 - val_mae: 311.4681
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 414511.2188 - mae: 311.4681

Processing MM
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 25936.2891 - mae: 77.3060 - val_loss: 1447.0956 - val_mae: 26.6885
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9409.8818 - mae: 53.0669 - val_loss: 2430.8008 - val_mae: 33.0311
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4987.7354 - mae: 44.7380 - val_loss: 2580.2883 - val_mae: 33.8342
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4836.8750 - mae: 43.6582 - val_loss: 3018.3677 - val_mae: 35.9155
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4717.2798 - mae: 43.0261 - val_loss: 3030.4331 - val_mae: 37.1226
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4638.8306 - mae: 42.5299 - val_loss: 3185.3057 - val_mae: 37.8803
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4562.9380 - mae: 41.9405 - val_loss: 3049.9736 - val_mae: 38.4850
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4517.9771 - mae: 41.5778 - val_loss: 2861.2842 - val_mae: 38.5848
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4468.8521 - mae: 41.0711 - val_loss: 2998.5823 - val_mae: 39.5587
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4389.1948 - mae: 40.6259 - val_loss: 2708.8013 - val_mae: 38.8064
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4326.2456 - mae: 40.2184 - val_loss: 2504.8323 - val_mae: 37.7000
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4276.0684 - mae: 39.9339 - val_loss: 2414.3445 - val_mae: 37.6927
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4209.9224 - mae: 39.5664 - val_loss: 2292.3870 - val_mae: 37.1986
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4176.2505 - mae: 39.2914 - val_loss: 2492.0583 - val_mae: 37.9432
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4088.6868 - mae: 38.9318 - val_loss: 2158.7415 - val_mae: 37.1399
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2158.7415 - mae: 37.1399

Processing NESTLEIND
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

33/33 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1975.6283 - mae: 28.7126 - val_loss: 6859.3140 - val_mae: 49.8123
Epoch 2/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1742.4932 - mae: 27.2771 - val_loss: 5399.2437 - val_mae: 44.9579
Epoch 3/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1111.8887 - mae: 22.1518 - val_loss: 2786.8787 - val_mae: 34.2376
Epoch 4/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 597.2612 - mae: 15.9823 - val_loss: 1560.2990 - val_mae: 27.1003
Epoch 5/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 399.9652 - mae: 13.3921 - val_loss: 997.4996 - val_mae: 23.1314
Epoch 6/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 293.9278 - mae: 11.9866 - val_loss: 680.8157 - val_mae: 19.8665
Epoch 7/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 237.8491 - mae: 11.1209 - val_loss: 551.2412 - val_mae: 18.4266
Epoch 8/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 203.9708 - mae: 10.5524 - val_loss: 485.8368 - val_mae: 17.2372
Epoch 9/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 184.9111 - mae: 10.1620 - val_loss: 466.0822 - val_mae: 17.0605
Epoch 10/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 170.3240 - mae: 9.8502 - val_loss: 471.6808 - val_mae: 17.0004
Epoch 11/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 159.0540 - mae: 9.5714 - val_loss: 557.8728 - val_mae: 18.8133
Epoch 12/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 150.4186 - mae: 9.3826 - val_loss: 621.3678 - val_mae: 19.6557
Epoch 13/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 143.5022 - mae: 9.1730 - val_loss: 618.2728 - val_mae: 19.8052
Epoch 14/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 137.7229 - mae: 9.0708 - val_loss: 843.8749 - val_mae: 22.7828
Epoch 15/15
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 132.5513 - mae: 8.8959 - val_loss: 781.8487 - val_mae: 21.7296
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 781.8487 - mae: 21.7296

Processing NTPC
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

65/65 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 487.8734 - mae: 16.3426 - val_loss: 336.0962 - val_mae: 15.3616
Epoch 2/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 330.0247 - mae: 13.7914 - val_loss: 420.3188 - val_mae: 15.4257
Epoch 3/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 213.8328 - mae: 10.8329 - val_loss: 496.2931 - val_mae: 16.1543
Epoch 4/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 193.9529 - mae: 10.1568 - val_loss: 459.0750 - val_mae: 15.7806
Epoch 5/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 186.2685 - mae: 9.9107 - val_loss: 495.4359 - val_mae: 16.1698
Epoch 6/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 180.6692 - mae: 9.7368 - val_loss: 488.4989 - val_mae: 16.2019
Epoch 7/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 175.6455 - mae: 9.5712 - val_loss: 500.9013 - val_mae: 16.3978
Epoch 8/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 170.7823 - mae: 9.3965 - val_loss: 509.3770 - val_mae: 16.6764
Epoch 9/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 165.2038 - mae: 9.2286 - val_loss: 508.2581 - val_mae: 16.7566
Epoch 10/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.7835 - mae: 9.0653 - val_loss: 529.0240 - val_mae: 17.2437
Epoch 11/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 154.6010 - mae: 8.8810 - val_loss: 531.9233 - val_mae: 17.4604
Epoch 12/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 147.8595 - mae: 8.6774 - val_loss: 555.5374 - val_mae: 17.8293
Epoch 13/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 142.6047 - mae: 8.5317 - val_loss: 570.0106 - val_mae: 18.5628
Epoch 14/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 137.4989 - mae: 8.3799 - val_loss: 549.8945 - val_mae: 18.1813
Epoch 15/15
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 131.6857 - mae: 8.2165 - val_loss: 573.5380 - val_mae: 18.6422
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 573.5380 - mae: 18.6422

Processing ONGC
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14212.8975 - mae: 57.5573 - val_loss: 1912.0305 - val_mae: 35.5838
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8507.4424 - mae: 49.2025 - val_loss: 11299.2881 - val_mae: 77.1689
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4920.1035 - mae: 41.9118 - val_loss: 5833.7485 - val_mae: 51.8674
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4186.4736 - mae: 39.0843 - val_loss: 3867.9341 - val_mae: 40.2977
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3646.4189 - mae: 37.1293 - val_loss: 3722.0698 - val_mae: 38.9423
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3197.6445 - mae: 35.1018 - val_loss: 3363.5508 - val_mae: 37.9848
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2800.2917 - mae: 33.3155 - val_loss: 2230.4739 - val_mae: 33.8405
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2492.9915 - mae: 31.8867 - val_loss: 2063.2878 - val_mae: 33.0188
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2266.7051 - mae: 30.7689 - val_loss: 1909.7223 - val_mae: 32.3890
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2100.0088 - mae: 29.8690 - val_loss: 1724.2390 - val_mae: 32.0091
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1948.2570 - mae: 29.0379 - val_loss: 1543.7506 - val_mae: 30.5383
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1791.9071 - mae: 28.0953 - val_loss: 1506.3051 - val_mae: 30.6010
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1688.4303 - mae: 27.4318 - val_loss: 1522.6948 - val_mae: 31.5940
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1594.9506 - mae: 26.8442 - val_loss: 1509.8490 - val_mae: 31.6681
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1503.9340 - mae: 26.2844 - val_loss: 1560.2316 - val_mae: 32.0816
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1560.2316 - mae: 32.0816

Processing POWERGRID
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 1194.0087 - mae: 23.1115 - val_loss: 784.1704 - val_mae: 21.6155
Epoch 2/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 973.8654 - mae: 21.0723 - val_loss: 809.7245 - val_mae: 22.4047
Epoch 3/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 610.6073 - mae: 16.9441 - val_loss: 1222.9377 - val_mae: 22.7493
Epoch 4/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 470.9001 - mae: 15.0635 - val_loss: 1667.8267 - val_mae: 26.1277
Epoch 5/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 392.6121 - mae: 14.2220 - val_loss: 1809.0603 - val_mae: 27.9552
Epoch 6/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 351.0489 - mae: 13.7482 - val_loss: 1739.3811 - val_mae: 28.3240
Epoch 7/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 331.6310 - mae: 13.3198 - val_loss: 1611.0967 - val_mae: 27.0829
Epoch 8/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 317.9546 - mae: 13.1364 - val_loss: 1545.7622 - val_mae: 26.9323
Epoch 9/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 308.3489 - mae: 12.9399 - val_loss: 1664.5895 - val_mae: 27.5436
Epoch 10/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 301.6171 - mae: 12.8474 - val_loss: 1659.9640 - val_mae: 27.4796
Epoch 11/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 295.2553 - mae: 12.7555 - val_loss: 1539.0078 - val_mae: 26.8552
Epoch 12/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 290.8904 - mae: 12.6763 - val_loss: 1696.3961 - val_mae: 28.0568
Epoch 13/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 285.3540 - mae: 12.4937 - val_loss: 1622.2457 - val_mae: 27.1228
Epoch 14/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 282.0533 - mae: 12.4774 - val_loss: 1676.2086 - val_mae: 27.6639
Epoch 15/15
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 278.2479 - mae: 12.4265 - val_loss: 1584.6660 - val_mae: 27.1273
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1584.6660 - mae: 27.1273

Processing RELIANCE
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 18264.6348 - mae: 62.1435 - val_loss: 1094.7852 - val_mae: 19.8659
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11309.9199 - mae: 48.4836 - val_loss: 1059.1776 - val_mae: 20.8791
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5728.6807 - mae: 41.9987 - val_loss: 1146.0609 - val_mae: 19.7172
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5372.3916 - mae: 40.2696 - val_loss: 1470.7024 - val_mae: 22.0299
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5157.1221 - mae: 39.2899 - val_loss: 1661.9786 - val_mae: 23.7710
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4976.3760 - mae: 38.1955 - val_loss: 1651.0884 - val_mae: 23.4650
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4788.9126 - mae: 37.3134 - val_loss: 1829.5438 - val_mae: 24.4993
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4570.2290 - mae: 36.6301 - val_loss: 1883.2161 - val_mae: 25.4083
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4365.5181 - mae: 36.1403 - val_loss: 1918.6876 - val_mae: 26.4717
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4218.4160 - mae: 35.7993 - val_loss: 2058.9404 - val_mae: 28.5280
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4101.3037 - mae: 35.5178 - val_loss: 2060.4543 - val_mae: 29.1584
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4000.2952 - mae: 35.3780 - val_loss: 2159.4937 - val_mae: 30.1711
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3869.7437 - mae: 34.9009 - val_loss: 2144.6445 - val_mae: 30.3827
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3796.5574 - mae: 34.6031 - val_loss: 2141.5520 - val_mae: 30.9221
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3675.5869 - mae: 34.1245 - val_loss: 2172.4922 - val_mae: 30.9789
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2172.4922 - mae: 30.9789

Processing SBIN
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 15500.3730 - mae: 68.5510 - val_loss: 4884.7314 - val_mae: 60.2799
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5329.7031 - mae: 43.8502 - val_loss: 17716.1582 - val_mae: 90.3673
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2808.1189 - mae: 35.4996 - val_loss: 17551.3555 - val_mae: 84.9079
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2652.8120 - mae: 33.6766 - val_loss: 16607.5332 - val_mae: 84.1128
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2600.0857 - mae: 33.0541 - val_loss: 18040.0684 - val_mae: 88.4029
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2547.0059 - mae: 32.5352 - val_loss: 18088.0234 - val_mae: 89.8166
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2507.7275 - mae: 31.9985 - val_loss: 19933.6816 - val_mae: 95.4056
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2464.2917 - mae: 31.6317 - val_loss: 18729.0820 - val_mae: 95.7041
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2448.3503 - mae: 31.2289 - val_loss: 21987.7070 - val_mae: 103.0163
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2419.9197 - mae: 31.0395 - val_loss: 21819.8242 - val_mae: 103.9522
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2395.7856 - mae: 30.6542 - val_loss: 22703.2656 - val_mae: 105.6893
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2379.6602 - mae: 30.4912 - val_loss: 22674.0977 - val_mae: 106.5274
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2362.7036 - mae: 30.3122 - val_loss: 23851.6777 - val_mae: 109.2098
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2354.2979 - mae: 30.1574 - val_loss: 21749.8125 - val_mae: 106.2758
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2341.9087 - mae: 29.9549 - val_loss: 28262.7344 - val_mae: 116.2563
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28262.7344 - mae: 116.2563

Processing SHREECEM
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

87/87 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 193776.9375 - mae: 208.1153 - val_loss: 9567.5830 - val_mae: 69.1778
Epoch 2/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 143114.2656 - mae: 166.9078 - val_loss: 438625.8438 - val_mae: 407.7723
Epoch 3/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 63899.6484 - mae: 123.9299 - val_loss: 399921.4062 - val_mae: 352.4736
Epoch 4/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 59111.0938 - mae: 123.9491 - val_loss: 421579.0938 - val_mae: 361.5341
Epoch 5/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57657.5859 - mae: 122.9340 - val_loss: 345806.8438 - val_mae: 325.6637
Epoch 6/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56980.8984 - mae: 121.2999 - val_loss: 394008.6875 - val_mae: 346.7424
Epoch 7/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55817.8789 - mae: 119.7150 - val_loss: 355936.2812 - val_mae: 329.1402
Epoch 8/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54990.4453 - mae: 119.5085 - val_loss: 378533.4375 - val_mae: 338.3373
Epoch 9/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54183.4609 - mae: 119.0308 - val_loss: 376379.4375 - val_mae: 334.7337
Epoch 10/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53153.6250 - mae: 117.2811 - val_loss: 374415.0625 - val_mae: 331.8896
Epoch 11/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52124.2930 - mae: 117.0585 - val_loss: 334280.6250 - val_mae: 311.9299
Epoch 12/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50954.8477 - mae: 114.7484 - val_loss: 349081.0625 - val_mae: 320.4520
Epoch 13/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49498.6992 - mae: 112.7786 - val_loss: 345984.4688 - val_mae: 313.4447
Epoch 14/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 47928.7031 - mae: 111.8699 - val_loss: 340456.6250 - val_mae: 311.8419
Epoch 15/15
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45978.8008 - mae: 109.2216 - val_loss: 322356.3438 - val_mae: 298.7046
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 322356.3438 - mae: 298.7046

Processing SUNPHARMA
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4199.8594 - mae: 42.2766 - val_loss: 914.4085 - val_mae: 24.5156
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2153.8909 - mae: 33.2756 - val_loss: 5060.3760 - val_mae: 21.5518
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1707.2296 - mae: 31.4814 - val_loss: 3979.4810 - val_mae: 20.7252
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1641.5707 - mae: 30.9538 - val_loss: 2954.2710 - val_mae: 20.1838
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1555.1349 - mae: 30.0905 - val_loss: 3458.3896 - val_mae: 19.8042
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1458.4490 - mae: 28.9548 - val_loss: 3614.8545 - val_mae: 22.2834
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1359.4967 - mae: 27.6959 - val_loss: 6527.0117 - val_mae: 26.2539
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1276.1681 - mae: 26.5573 - val_loss: 10190.8320 - val_mae: 31.1843
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1206.9298 - mae: 25.5839 - val_loss: 11840.4639 - val_mae: 33.0705
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1148.6578 - mae: 24.8181 - val_loss: 13645.6123 - val_mae: 35.4712
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1097.5520 - mae: 24.2000 - val_loss: 14692.9502 - val_mae: 35.8499
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1051.1753 - mae: 23.5968 - val_loss: 15426.2080 - val_mae: 37.2688
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1007.8181 - mae: 23.0455 - val_loss: 15668.6201 - val_mae: 37.7467
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 972.4393 - mae: 22.6515 - val_loss: 15097.6221 - val_mae: 37.6215
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 936.2058 - mae: 22.2042 - val_loss: 14491.7959 - val_mae: 37.1845
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14491.7959 - mae: 37.1845

Processing TATAMOTORS
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30437.1074 - mae: 88.0257 - val_loss: 1388.0148 - val_mae: 29.5720
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15875.3887 - mae: 64.8050 - val_loss: 4818.8833 - val_mae: 45.1370
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8729.5762 - mae: 54.9711 - val_loss: 3663.2588 - val_mae: 39.2597
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8139.4209 - mae: 54.1290 - val_loss: 3246.3682 - val_mae: 37.2389
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7699.7490 - mae: 53.1969 - val_loss: 2687.2451 - val_mae: 34.7013
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7291.7681 - mae: 52.2401 - val_loss: 2617.8875 - val_mae: 34.3713
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6908.9438 - mae: 51.3770 - val_loss: 2570.2271 - val_mae: 34.3540
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6513.1040 - mae: 50.4911 - val_loss: 2479.1382 - val_mae: 34.3444
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6161.0742 - mae: 49.5375 - val_loss: 2510.3474 - val_mae: 34.8816
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5859.8232 - mae: 48.5336 - val_loss: 2240.9937 - val_mae: 33.5806
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5534.8750 - mae: 47.8179 - val_loss: 2324.8989 - val_mae: 34.4144
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5251.4067 - mae: 46.7911 - val_loss: 2428.6150 - val_mae: 35.1161
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4984.2852 - mae: 45.7393 - val_loss: 2318.4607 - val_mae: 34.6720
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4675.0332 - mae: 44.6057 - val_loss: 2208.6697 - val_mae: 34.2939
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4446.3081 - mae: 43.6463 - val_loss: 2276.3418 - val_mae: 34.9531
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2276.3418 - mae: 34.9531

Processing TATASTEEL
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12068.9521 - mae: 59.1336 - val_loss: 3244.9150 - val_mae: 40.0350
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6704.6323 - mae: 45.0279 - val_loss: 2153.1833 - val_mae: 32.9760
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3007.2971 - mae: 36.3376 - val_loss: 2421.0803 - val_mae: 34.9047
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2425.1775 - mae: 33.4004 - val_loss: 2311.4458 - val_mae: 35.2275
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2353.8579 - mae: 32.6017 - val_loss: 2354.5950 - val_mae: 35.5112
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2311.6809 - mae: 32.4808 - val_loss: 2239.4741 - val_mae: 35.0174
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2238.5852 - mae: 32.0690 - val_loss: 1901.3293 - val_mae: 33.4301
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2113.6941 - mae: 31.4412 - val_loss: 1934.9480 - val_mae: 33.6231
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1971.5140 - mae: 30.7674 - val_loss: 1961.2831 - val_mae: 33.3601
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1852.0530 - mae: 29.9040 - val_loss: 1780.7866 - val_mae: 31.6711
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1782.4905 - mae: 29.2545 - val_loss: 1868.1150 - val_mae: 32.2419
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1735.9220 - mae: 28.8086 - val_loss: 1865.2034 - val_mae: 32.4161
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1693.8289 - mae: 28.5468 - val_loss: 1809.9100 - val_mae: 31.7883
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1678.2866 - mae: 28.1507 - val_loss: 1920.1910 - val_mae: 33.0087
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1647.5676 - mae: 27.9036 - val_loss: 2134.7285 - val_mae: 34.7408
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2134.7285 - mae: 34.7408

Processing TCS
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6712.9893 - mae: 49.9967 - val_loss: 194.0757 - val_mae: 10.6539
Epoch 2/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4452.1548 - mae: 44.3484 - val_loss: 203.2888 - val_mae: 10.6242
Epoch 3/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1774.8258 - mae: 31.5749 - val_loss: 188.2562 - val_mae: 10.1463
Epoch 4/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1446.3901 - mae: 28.4971 - val_loss: 249.9641 - val_mae: 11.7906
Epoch 5/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1266.1901 - mae: 27.0233 - val_loss: 566.1234 - val_mae: 19.3557
Epoch 6/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1105.7601 - mae: 25.3759 - val_loss: 1791.0850 - val_mae: 36.4834
Epoch 7/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 999.3754 - mae: 24.0806 - val_loss: 2201.3403 - val_mae: 37.9105
Epoch 8/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 924.7161 - mae: 23.0974 - val_loss: 2464.5461 - val_mae: 38.0603
Epoch 9/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 881.7601 - mae: 22.4830 - val_loss: 2764.3003 - val_mae: 39.9006
Epoch 10/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 842.7344 - mae: 21.9830 - val_loss: 2689.6462 - val_mae: 38.4637
Epoch 11/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 813.6193 - mae: 21.5725 - val_loss: 2719.4583 - val_mae: 38.4008
Epoch 12/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 789.4903 - mae: 21.1704 - val_loss: 2859.8560 - val_mae: 39.5318
Epoch 13/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 767.0146 - mae: 20.8613 - val_loss: 3365.1609 - val_mae: 43.9471
Epoch 14/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 745.6024 - mae: 20.5142 - val_loss: 2492.0129 - val_mae: 36.6181
Epoch 15/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 723.3939 - mae: 20.1686 - val_loss: 3234.6934 - val_mae: 43.1162
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3234.6934 - mae: 43.1162

Processing TECHM
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11877.7979 - mae: 61.1113 - val_loss: 2994.0574 - val_mae: 42.8002
Epoch 2/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11224.1660 - mae: 60.1938 - val_loss: 3410.2627 - val_mae: 49.2439
Epoch 3/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8577.3359 - mae: 60.3384 - val_loss: 5494.1851 - val_mae: 67.8353
Epoch 4/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6450.5557 - mae: 57.7186 - val_loss: 7463.3047 - val_mae: 74.0558
Epoch 5/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5654.0430 - mae: 52.5978 - val_loss: 8524.4092 - val_mae: 79.5100
Epoch 6/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5156.0776 - mae: 50.2582 - val_loss: 9756.9453 - val_mae: 84.7323
Epoch 7/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4660.9453 - mae: 47.5536 - val_loss: 10873.5859 - val_mae: 88.7888
Epoch 8/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4193.4927 - mae: 44.7254 - val_loss: 11408.0986 - val_mae: 89.5638
Epoch 9/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3784.7295 - mae: 42.2767 - val_loss: 10844.9004 - val_mae: 86.0520
Epoch 10/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3419.5029 - mae: 40.1964 - val_loss: 12141.1631 - val_mae: 89.6498
Epoch 11/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3067.0632 - mae: 38.5106 - val_loss: 13456.5791 - val_mae: 93.1750
Epoch 12/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2770.1492 - mae: 36.8796 - val_loss: 12230.0938 - val_mae: 87.8987
Epoch 13/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2510.9617 - mae: 35.3037 - val_loss: 13377.1777 - val_mae: 89.2245
Epoch 14/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2326.5645 - mae: 34.0017 - val_loss: 12446.1094 - val_mae: 86.2444
Epoch 15/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2146.0225 - mae: 32.7181 - val_loss: 11515.0820 - val_mae: 82.8669
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11515.0820 - mae: 82.8669

Processing TITAN
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 196407.1406 - mae: 191.2521 - val_loss: 14934.8408 - val_mae: 73.6511
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 150526.5000 - mae: 167.3196 - val_loss: 7771.6240 - val_mae: 59.1518
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 55075.1445 - mae: 122.1641 - val_loss: 37946.0312 - val_mae: 116.1845
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 40103.9922 - mae: 110.0465 - val_loss: 39916.1172 - val_mae: 114.2560
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 37419.2930 - mae: 106.5754 - val_loss: 37908.4805 - val_mae: 109.8016
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 35719.8516 - mae: 104.4823 - val_loss: 35777.5664 - val_mae: 106.2167
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 34492.1758 - mae: 102.9483 - val_loss: 34963.9141 - val_mae: 103.4994
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 33454.9609 - mae: 101.6434 - val_loss: 32224.1348 - val_mae: 98.3658
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32619.9570 - mae: 100.5705 - val_loss: 33337.0742 - val_mae: 98.7221
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31714.7695 - mae: 98.8984 - val_loss: 31086.2578 - val_mae: 95.3687
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31002.9082 - mae: 97.9117 - val_loss: 30735.5898 - val_mae: 93.5839
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30424.6094 - mae: 96.9524 - val_loss: 33953.0078 - val_mae: 97.5999
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29925.6055 - mae: 96.2019 - val_loss: 26718.0742 - val_mae: 86.4126
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29484.5508 - mae: 95.3415 - val_loss: 24603.6074 - val_mae: 83.8557
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29154.4961 - mae: 94.8700 - val_loss: 26622.9434 - val_mae: 87.0396
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26622.9434 - mae: 87.0396

Processing ULTRACEMCO
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8950.7666 - mae: 62.3670 - val_loss: 1320.7501 - val_mae: 27.1578
Epoch 2/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6825.0146 - mae: 54.2011 - val_loss: 10412.3213 - val_mae: 88.7439
Epoch 3/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3479.2161 - mae: 42.2481 - val_loss: 9799.4219 - val_mae: 70.1806
Epoch 4/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2808.5125 - mae: 38.9806 - val_loss: 8636.2119 - val_mae: 61.5277
Epoch 5/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2578.7375 - mae: 37.8959 - val_loss: 6788.8770 - val_mae: 53.7966
Epoch 6/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2454.5120 - mae: 37.0297 - val_loss: 5240.6104 - val_mae: 47.1466
Epoch 7/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2351.9729 - mae: 36.4841 - val_loss: 4732.6890 - val_mae: 44.6353
Epoch 8/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2291.9478 - mae: 35.9985 - val_loss: 3919.0225 - val_mae: 40.3979
Epoch 9/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2249.5137 - mae: 35.6661 - val_loss: 3452.9954 - val_mae: 37.8680
Epoch 10/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2205.7678 - mae: 35.3863 - val_loss: 3567.3682 - val_mae: 38.5263
Epoch 11/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2173.0295 - mae: 35.0994 - val_loss: 3350.1177 - val_mae: 37.2664
Epoch 12/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2137.3789 - mae: 34.7852 - val_loss: 3382.0361 - val_mae: 37.5479
Epoch 13/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2117.0088 - mae: 34.6556 - val_loss: 3508.9282 - val_mae: 38.4676
Epoch 14/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2090.5610 - mae: 34.4314 - val_loss: 3337.6045 - val_mae: 37.6000
Epoch 15/15
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2069.9832 - mae: 34.2355 - val_loss: 3400.5452 - val_mae: 38.1976
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3400.5452 - mae: 38.1976

Processing UPL
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

70/70 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 17024.7305 - mae: 71.0913 - val_loss: 9010.9229 - val_mae: 61.9754
Epoch 2/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12328.2588 - mae: 61.2613 - val_loss: 10097.3916 - val_mae: 61.5741
Epoch 3/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5179.9072 - mae: 46.5851 - val_loss: 9251.6699 - val_mae: 59.7575
Epoch 4/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4094.6001 - mae: 43.1003 - val_loss: 7461.9409 - val_mae: 64.7869
Epoch 5/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3721.5308 - mae: 41.4183 - val_loss: 8529.5674 - val_mae: 74.5624
Epoch 6/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3483.0818 - mae: 39.9216 - val_loss: 10071.8701 - val_mae: 81.1487
Epoch 7/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3280.5156 - mae: 38.7232 - val_loss: 12323.9033 - val_mae: 88.6267
Epoch 8/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3091.7026 - mae: 37.5826 - val_loss: 14199.1807 - val_mae: 93.5561
Epoch 9/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2915.1519 - mae: 36.4598 - val_loss: 16162.6777 - val_mae: 98.3485
Epoch 10/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2769.5876 - mae: 35.4916 - val_loss: 17695.1309 - val_mae: 101.5743
Epoch 11/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2609.7632 - mae: 34.4354 - val_loss: 18655.4121 - val_mae: 103.2242
Epoch 12/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2474.1738 - mae: 33.5905 - val_loss: 21088.7129 - val_mae: 108.0463
Epoch 13/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2352.7751 - mae: 32.7900 - val_loss: 21136.9160 - val_mae: 107.6352
Epoch 14/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2249.8760 - mae: 32.1280 - val_loss: 20942.5312 - val_mae: 106.6895
Epoch 15/15
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2166.6931 - mae: 31.5641 - val_loss: 20727.7168 - val_mae: 107.4261
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20727.7168 - mae: 107.4261

Processing VEDL
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 444850.6250 - mae: 219.0260 - val_loss: 4851.2349 - val_mae: 48.5967
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 387030.2812 - mae: 217.4535 - val_loss: 39927.6250 - val_mae: 146.3564
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 239141.1719 - mae: 219.0480 - val_loss: 112752.5938 - val_mae: 185.5264
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 190423.5938 - mae: 193.9561 - val_loss: 104635.6016 - val_mae: 162.0980
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 165159.8438 - mae: 178.1306 - val_loss: 92891.4688 - val_mae: 147.9354
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 144303.6719 - mae: 166.0944 - val_loss: 76073.3516 - val_mae: 126.3760
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 127903.8984 - mae: 153.7321 - val_loss: 74401.6250 - val_mae: 116.4701
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 115455.3438 - mae: 146.1319 - val_loss: 60715.6992 - val_mae: 102.9781
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 106258.1484 - mae: 140.9319 - val_loss: 55956.6484 - val_mae: 96.3607
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99521.8672 - mae: 135.2687 - val_loss: 62646.2617 - val_mae: 97.4844
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 94952.7656 - mae: 133.1381 - val_loss: 52201.3438 - val_mae: 89.3067
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 90506.4609 - mae: 129.5417 - val_loss: 56478.3086 - val_mae: 91.2614
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 87842.5547 - mae: 128.5010 - val_loss: 43845.4844 - val_mae: 83.2903
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 84728.0078 - mae: 126.7768 - val_loss: 31328.5898 - val_mae: 74.8112
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 83272.2734 - mae: 124.6660 - val_loss: 37082.4414 - val_mae: 79.5843
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37082.4414 - mae: 79.5843

Processing WIPRO
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1646.4811 - mae: 29.8488 - val_loss: 858.0055 - val_mae: 21.9003
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1274.7651 - mae: 25.3681 - val_loss: 792.9998 - val_mae: 21.1021
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1066.2726 - mae: 23.6151 - val_loss: 742.8194 - val_mae: 20.5459
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 903.3868 - mae: 22.1113 - val_loss: 708.0227 - val_mae: 20.5059
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 806.0611 - mae: 20.9011 - val_loss: 658.8080 - val_mae: 20.9621
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 729.3109 - mae: 19.9341 - val_loss: 689.5856 - val_mae: 22.4312
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 664.5867 - mae: 19.1012 - val_loss: 705.0505 - val_mae: 23.0413
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 613.1949 - mae: 18.5544 - val_loss: 735.8457 - val_mae: 23.8545
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 574.5604 - mae: 18.0873 - val_loss: 697.3802 - val_mae: 23.2358
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 544.4250 - mae: 17.7438 - val_loss: 684.7921 - val_mae: 23.0979
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 518.3331 - mae: 17.3870 - val_loss: 700.8552 - val_mae: 23.3998
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 497.1268 - mae: 17.0677 - val_loss: 701.6816 - val_mae: 23.4397
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 478.7567 - mae: 16.8262 - val_loss: 709.2089 - val_mae: 23.6802
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 464.7195 - mae: 16.6016 - val_loss: 688.5605 - val_mae: 23.0854
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 452.1303 - mae: 16.4257 - val_loss: 708.2495 - val_mae: 23.6180
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 708.2495 - mae: 23.6180

Processing ZEEL
Epoch 1/15

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6121.1772 - mae: 50.9298 - val_loss: 2551.6318 - val_mae: 39.6497
Epoch 2/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3262.4509 - mae: 38.9638 - val_loss: 4152.3926 - val_mae: 53.1565
Epoch 3/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2152.6499 - mae: 34.3480 - val_loss: 4147.7827 - val_mae: 52.9132
Epoch 4/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2095.2036 - mae: 33.7863 - val_loss: 4109.6650 - val_mae: 52.5416
Epoch 5/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2038.7061 - mae: 33.1770 - val_loss: 4045.3284 - val_mae: 52.0297
Epoch 6/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1995.3046 - mae: 32.7522 - val_loss: 4006.5073 - val_mae: 52.0186
Epoch 7/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1946.8325 - mae: 32.3523 - val_loss: 3988.0955 - val_mae: 52.0098
Epoch 8/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1897.8416 - mae: 31.9238 - val_loss: 3951.2632 - val_mae: 51.8714
Epoch 9/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1856.3237 - mae: 31.4928 - val_loss: 3684.0737 - val_mae: 49.8274
Epoch 10/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1812.1354 - mae: 31.1034 - val_loss: 3758.6470 - val_mae: 50.8373
Epoch 11/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1778.0137 - mae: 30.7191 - val_loss: 3899.4268 - val_mae: 51.7183
Epoch 12/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1751.4628 - mae: 30.4521 - val_loss: 3694.8276 - val_mae: 50.5342
Epoch 13/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1718.8250 - mae: 30.1025 - val_loss: 3527.5239 - val_mae: 49.2309
Epoch 14/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1690.8204 - mae: 29.8639 - val_loss: 3649.0300 - val_mae: 50.2116
Epoch 15/15
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1668.3223 - mae: 29.6288 - val_loss: 3719.4729 - val_mae: 50.3861
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3719.4729 - mae: 50.3861